package com.ddshteam.web.system.service.api.model;

import java.io.Serializable;
import java.util.Date;

public class SysDepInfo implements Serializable {
    /**
     * 主键ID
     * 表字段 : sys_dep_info.id
     */
    private String id;

    /**
     * 部门名称
     * 表字段 : sys_dep_info.name
     */
    private String name;

    /**
     * 上级部门ID
     * 表字段 : sys_dep_info.parent_id
     */
    private String parentId;

    /**
     * 部门分类，当前系统无部门分类时，此列无意义为空
     * 表字段 : sys_dep_info.type_id
     */
    private String typeId;

    /**
     * 备注
     * 表字段 : sys_dep_info.remark
     */
    private String remark;

    /**
     * 序号
     * 表字段 : sys_dep_info.order_num
     */
    private Integer orderNum;

    /**
     * 状态：1有效0失效
     * 表字段 : sys_dep_info.status
     */
    private Integer status;

    /**
     * 层级路径
     * 表字段 : sys_dep_info.path
     */
    private String path;

    /**
     * 创建时间
     * 表字段 : sys_dep_info.create_time
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dep_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键ID 字段:sys_dep_info.id
     *
     * @return sys_dep_info.id, 主键ID
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 主键ID 字段:sys_dep_info.id
     *
     * @param id the value for sys_dep_info.id, 主键ID
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 部门名称 字段:sys_dep_info.name
     *
     * @return sys_dep_info.name, 部门名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 部门名称 字段:sys_dep_info.name
     *
     * @param name the value for sys_dep_info.name, 部门名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 上级部门ID 字段:sys_dep_info.parent_id
     *
     * @return sys_dep_info.parent_id, 上级部门ID
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * 设置 上级部门ID 字段:sys_dep_info.parent_id
     *
     * @param parentId the value for sys_dep_info.parent_id, 上级部门ID
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * 获取 部门分类，当前系统无部门分类时，此列无意义为空 字段:sys_dep_info.type_id
     *
     * @return sys_dep_info.type_id, 部门分类，当前系统无部门分类时，此列无意义为空
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * 设置 部门分类，当前系统无部门分类时，此列无意义为空 字段:sys_dep_info.type_id
     *
     * @param typeId the value for sys_dep_info.type_id, 部门分类，当前系统无部门分类时，此列无意义为空
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * 获取 备注 字段:sys_dep_info.remark
     *
     * @return sys_dep_info.remark, 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 备注 字段:sys_dep_info.remark
     *
     * @param remark the value for sys_dep_info.remark, 备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取 序号 字段:sys_dep_info.order_num
     *
     * @return sys_dep_info.order_num, 序号
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * 设置 序号 字段:sys_dep_info.order_num
     *
     * @param orderNum the value for sys_dep_info.order_num, 序号
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * 获取 状态：1有效0失效 字段:sys_dep_info.status
     *
     * @return sys_dep_info.status, 状态：1有效0失效
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态：1有效0失效 字段:sys_dep_info.status
     *
     * @param status the value for sys_dep_info.status, 状态：1有效0失效
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 层级路径 字段:sys_dep_info.path
     *
     * @return sys_dep_info.path, 层级路径
     */
    public String getPath() {
        return path;
    }

    /**
     * 设置 层级路径 字段:sys_dep_info.path
     *
     * @param path the value for sys_dep_info.path, 层级路径
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * 获取 创建时间 字段:sys_dep_info.create_time
     *
     * @return sys_dep_info.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:sys_dep_info.create_time
     *
     * @param createTime the value for sys_dep_info.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * ,sys_dep_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", parentId=").append(parentId);
        sb.append(", typeId=").append(typeId);
        sb.append(", remark=").append(remark);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", status=").append(status);
        sb.append(", path=").append(path);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}