package com.ddsh.pdf.service.api.model;

import java.io.Serializable;
import java.util.Date;

public class AttAttachmentInfo implements Serializable {
    /**
     * 
     * 表字段 : att_attachment_info.id
     */
    private String id;

    /**
     * 附件关联业务表
     * 表字段 : att_attachment_info.table_name
     */
    private String tableName;

    /**
     * 附件类型
     * 表字段 : att_attachment_info.type
     */
    private String type;

    /**
     * 附件关联业务ID
     * 表字段 : att_attachment_info.obj_id
     */
    private String objId;

    /**
     * 附件关联业务附属性ID
     * 表字段 : att_attachment_info.obj_sub_id
     */
    private String objSubId;

    /**
     * 附件相对路径
     * 表字段 : att_attachment_info.path
     */
    private String path;

    /**
     * 更新时间
     * 表字段 : att_attachment_info.update_time
     */
    private Date updateTime;

    /**
     * 上传用户id
     * 表字段 : att_attachment_info.upload_userId
     */
    private String uploadUserid;

    /**
     * 上传用户名称
     * 表字段 : att_attachment_info.upload_userName
     */
    private String uploadUsername;

    /**
     * 状态，1可用，0不可用
     * 表字段 : att_attachment_info.status
     */
    private Integer status;

    /**
     * 文件名称
     * 表字段 : att_attachment_info.file_name
     */
    private String fileName;

    /**
     * 文件类型，1:图片、2:动图、3:视频、4:文档、5、应用包、6:压缩包
     * 表字段 : att_attachment_info.file_type
     */
    private String fileType;

    /**
     * 文件大小，单位：兆<M>
     * 表字段 : att_attachment_info.file_size
     */
    private Integer fileSize;

    /**
     * 文件备注
     * 表字段 : att_attachment_info.remark
     */
    private String remark;

    /**
     * 文件中文别名
     * 表字段 : att_attachment_info.name
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table att_attachment_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:att_attachment_info.id
     *
     * @return att_attachment_info.id, 
     */
    public String getId() {
        return id;
    }

    /**
     * 设置  字段:att_attachment_info.id
     *
     * @param id the value for att_attachment_info.id, 
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 附件关联业务表 字段:att_attachment_info.table_name
     *
     * @return att_attachment_info.table_name, 附件关联业务表
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * 设置 附件关联业务表 字段:att_attachment_info.table_name
     *
     * @param tableName the value for att_attachment_info.table_name, 附件关联业务表
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * 获取 附件类型 字段:att_attachment_info.type
     *
     * @return att_attachment_info.type, 附件类型
     */
    public String getType() {
        return type;
    }

    /**
     * 设置 附件类型 字段:att_attachment_info.type
     *
     * @param type the value for att_attachment_info.type, 附件类型
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 获取 附件关联业务ID 字段:att_attachment_info.obj_id
     *
     * @return att_attachment_info.obj_id, 附件关联业务ID
     */
    public String getObjId() {
        return objId;
    }

    /**
     * 设置 附件关联业务ID 字段:att_attachment_info.obj_id
     *
     * @param objId the value for att_attachment_info.obj_id, 附件关联业务ID
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * 获取 附件关联业务附属性ID 字段:att_attachment_info.obj_sub_id
     *
     * @return att_attachment_info.obj_sub_id, 附件关联业务附属性ID
     */
    public String getObjSubId() {
        return objSubId;
    }

    /**
     * 设置 附件关联业务附属性ID 字段:att_attachment_info.obj_sub_id
     *
     * @param objSubId the value for att_attachment_info.obj_sub_id, 附件关联业务附属性ID
     */
    public void setObjSubId(String objSubId) {
        this.objSubId = objSubId == null ? null : objSubId.trim();
    }

    /**
     * 获取 附件相对路径 字段:att_attachment_info.path
     *
     * @return att_attachment_info.path, 附件相对路径
     */
    public String getPath() {
        return path;
    }

    /**
     * 设置 附件相对路径 字段:att_attachment_info.path
     *
     * @param path the value for att_attachment_info.path, 附件相对路径
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * 获取 更新时间 字段:att_attachment_info.update_time
     *
     * @return att_attachment_info.update_time, 更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 更新时间 字段:att_attachment_info.update_time
     *
     * @param updateTime the value for att_attachment_info.update_time, 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取 上传用户id 字段:att_attachment_info.upload_userId
     *
     * @return att_attachment_info.upload_userId, 上传用户id
     */
    public String getUploadUserid() {
        return uploadUserid;
    }

    /**
     * 设置 上传用户id 字段:att_attachment_info.upload_userId
     *
     * @param uploadUserid the value for att_attachment_info.upload_userId, 上传用户id
     */
    public void setUploadUserid(String uploadUserid) {
        this.uploadUserid = uploadUserid == null ? null : uploadUserid.trim();
    }

    /**
     * 获取 上传用户名称 字段:att_attachment_info.upload_userName
     *
     * @return att_attachment_info.upload_userName, 上传用户名称
     */
    public String getUploadUsername() {
        return uploadUsername;
    }

    /**
     * 设置 上传用户名称 字段:att_attachment_info.upload_userName
     *
     * @param uploadUsername the value for att_attachment_info.upload_userName, 上传用户名称
     */
    public void setUploadUsername(String uploadUsername) {
        this.uploadUsername = uploadUsername == null ? null : uploadUsername.trim();
    }

    /**
     * 获取 状态，1可用，0不可用 字段:att_attachment_info.status
     *
     * @return att_attachment_info.status, 状态，1可用，0不可用
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态，1可用，0不可用 字段:att_attachment_info.status
     *
     * @param status the value for att_attachment_info.status, 状态，1可用，0不可用
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 文件名称 字段:att_attachment_info.file_name
     *
     * @return att_attachment_info.file_name, 文件名称
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * 设置 文件名称 字段:att_attachment_info.file_name
     *
     * @param fileName the value for att_attachment_info.file_name, 文件名称
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * 获取 文件类型，1:图片、2:动图、3:视频、4:文档、5、应用包、6:压缩包 字段:att_attachment_info.file_type
     *
     * @return att_attachment_info.file_type, 文件类型，1:图片、2:动图、3:视频、4:文档、5、应用包、6:压缩包
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * 设置 文件类型，1:图片、2:动图、3:视频、4:文档、5、应用包、6:压缩包 字段:att_attachment_info.file_type
     *
     * @param fileType the value for att_attachment_info.file_type, 文件类型，1:图片、2:动图、3:视频、4:文档、5、应用包、6:压缩包
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * 获取 文件大小，单位：兆<M> 字段:att_attachment_info.file_size
     *
     * @return att_attachment_info.file_size, 文件大小，单位：兆<M>
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * 设置 文件大小，单位：兆<M> 字段:att_attachment_info.file_size
     *
     * @param fileSize the value for att_attachment_info.file_size, 文件大小，单位：兆<M>
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * 获取 文件备注 字段:att_attachment_info.remark
     *
     * @return att_attachment_info.remark, 文件备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 文件备注 字段:att_attachment_info.remark
     *
     * @param remark the value for att_attachment_info.remark, 文件备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取 文件中文别名 字段:att_attachment_info.name
     *
     * @return att_attachment_info.name, 文件中文别名
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 文件中文别名 字段:att_attachment_info.name
     *
     * @param name the value for att_attachment_info.name, 文件中文别名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * ,att_attachment_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tableName=").append(tableName);
        sb.append(", type=").append(type);
        sb.append(", objId=").append(objId);
        sb.append(", objSubId=").append(objSubId);
        sb.append(", path=").append(path);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", uploadUserid=").append(uploadUserid);
        sb.append(", uploadUsername=").append(uploadUsername);
        sb.append(", status=").append(status);
        sb.append(", fileName=").append(fileName);
        sb.append(", fileType=").append(fileType);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", remark=").append(remark);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}