package com.ddsh.util.service.api.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InqInquiryOrderCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inq_inquiry_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inq_inquiry_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inq_inquiry_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inq_inquiry_order
     *
     * @mbg.generated
     */
    protected Integer pageNo = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inq_inquiry_order
     *
     * @mbg.generated
     */
    protected Integer startRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inq_inquiry_order
     *
     * @mbg.generated
     */
    protected Integer pageSize = 10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inq_inquiry_order
     *
     * @mbg.generated
     */
    protected String fields;

    /**
     *  构造查询条件,inq_inquiry_order
     */
    public InqInquiryOrderCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,inq_inquiry_order
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,inq_inquiry_order
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,inq_inquiry_order
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,inq_inquiry_order
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,inq_inquiry_order
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,inq_inquiry_order
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,inq_inquiry_order
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,inq_inquiry_order
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,inq_inquiry_order
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,inq_inquiry_order
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,inq_inquiry_order
     *
     * @param pageNo
     */
    public void setPageNo(Integer pageNo) {
        this.pageNo=pageNo;
        this.startRow = (pageNo-1)*this.pageSize;
    }

    /**
     * ,inq_inquiry_order
     */
    public Integer getPageNo() {
        return pageNo;
    }

    /**
     * ,inq_inquiry_order
     *
     * @param startRow
     */
    public void setStartRow(Integer startRow) {
        this.startRow=startRow;
    }

    /**
     * ,inq_inquiry_order
     */
    public Integer getStartRow() {
        return startRow;
    }

    /**
     * ,inq_inquiry_order
     *
     * @param pageSize
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize=pageSize;
        this.startRow = (pageNo-1)*this.pageSize;
    }

    /**
     * ,inq_inquiry_order
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * ,inq_inquiry_order
     *
     * @param fields
     */
    public void setFields(String fields) {
        this.fields=fields;
    }

    /**
     * ,inq_inquiry_order
     */
    public String getFields() {
        return fields;
    }

    /**
     * 询价申请单
     * GeneratedCriteria
     * 数据库表：inq_inquiry_order
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andUseDepNameIsNull() {
            addCriterion("use_dep_name is null");
            return (Criteria) this;
        }

        public Criteria andUseDepNameIsNotNull() {
            addCriterion("use_dep_name is not null");
            return (Criteria) this;
        }

        public Criteria andUseDepNameEqualTo(String value) {
            addCriterion("use_dep_name =", value, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameNotEqualTo(String value) {
            addCriterion("use_dep_name <>", value, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameGreaterThan(String value) {
            addCriterion("use_dep_name >", value, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameGreaterThanOrEqualTo(String value) {
            addCriterion("use_dep_name >=", value, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameLessThan(String value) {
            addCriterion("use_dep_name <", value, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameLessThanOrEqualTo(String value) {
            addCriterion("use_dep_name <=", value, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameLike(String value) {
            addCriterion("use_dep_name like", value, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameNotLike(String value) {
            addCriterion("use_dep_name not like", value, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameIn(List<String> values) {
            addCriterion("use_dep_name in", values, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameNotIn(List<String> values) {
            addCriterion("use_dep_name not in", values, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameBetween(String value1, String value2) {
            addCriterion("use_dep_name between", value1, value2, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepNameNotBetween(String value1, String value2) {
            addCriterion("use_dep_name not between", value1, value2, "useDepName");
            return (Criteria) this;
        }

        public Criteria andUseDepIdIsNull() {
            addCriterion("use_dep_id is null");
            return (Criteria) this;
        }

        public Criteria andUseDepIdIsNotNull() {
            addCriterion("use_dep_id is not null");
            return (Criteria) this;
        }

        public Criteria andUseDepIdEqualTo(String value) {
            addCriterion("use_dep_id =", value, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdNotEqualTo(String value) {
            addCriterion("use_dep_id <>", value, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdGreaterThan(String value) {
            addCriterion("use_dep_id >", value, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdGreaterThanOrEqualTo(String value) {
            addCriterion("use_dep_id >=", value, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdLessThan(String value) {
            addCriterion("use_dep_id <", value, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdLessThanOrEqualTo(String value) {
            addCriterion("use_dep_id <=", value, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdLike(String value) {
            addCriterion("use_dep_id like", value, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdNotLike(String value) {
            addCriterion("use_dep_id not like", value, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdIn(List<String> values) {
            addCriterion("use_dep_id in", values, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdNotIn(List<String> values) {
            addCriterion("use_dep_id not in", values, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdBetween(String value1, String value2) {
            addCriterion("use_dep_id between", value1, value2, "useDepId");
            return (Criteria) this;
        }

        public Criteria andUseDepIdNotBetween(String value1, String value2) {
            addCriterion("use_dep_id not between", value1, value2, "useDepId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdIsNull() {
            addCriterion("initiateuser_id is null");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdIsNotNull() {
            addCriterion("initiateuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdEqualTo(String value) {
            addCriterion("initiateuser_id =", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdNotEqualTo(String value) {
            addCriterion("initiateuser_id <>", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdGreaterThan(String value) {
            addCriterion("initiateuser_id >", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdGreaterThanOrEqualTo(String value) {
            addCriterion("initiateuser_id >=", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdLessThan(String value) {
            addCriterion("initiateuser_id <", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdLessThanOrEqualTo(String value) {
            addCriterion("initiateuser_id <=", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdLike(String value) {
            addCriterion("initiateuser_id like", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdNotLike(String value) {
            addCriterion("initiateuser_id not like", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdIn(List<String> values) {
            addCriterion("initiateuser_id in", values, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdNotIn(List<String> values) {
            addCriterion("initiateuser_id not in", values, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdBetween(String value1, String value2) {
            addCriterion("initiateuser_id between", value1, value2, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdNotBetween(String value1, String value2) {
            addCriterion("initiateuser_id not between", value1, value2, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdIsNull() {
            addCriterion("initiatedept_id is null");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdIsNotNull() {
            addCriterion("initiatedept_id is not null");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdEqualTo(String value) {
            addCriterion("initiatedept_id =", value, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdNotEqualTo(String value) {
            addCriterion("initiatedept_id <>", value, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdGreaterThan(String value) {
            addCriterion("initiatedept_id >", value, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdGreaterThanOrEqualTo(String value) {
            addCriterion("initiatedept_id >=", value, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdLessThan(String value) {
            addCriterion("initiatedept_id <", value, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdLessThanOrEqualTo(String value) {
            addCriterion("initiatedept_id <=", value, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdLike(String value) {
            addCriterion("initiatedept_id like", value, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdNotLike(String value) {
            addCriterion("initiatedept_id not like", value, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdIn(List<String> values) {
            addCriterion("initiatedept_id in", values, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdNotIn(List<String> values) {
            addCriterion("initiatedept_id not in", values, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdBetween(String value1, String value2) {
            addCriterion("initiatedept_id between", value1, value2, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiatedeptIdNotBetween(String value1, String value2) {
            addCriterion("initiatedept_id not between", value1, value2, "initiatedeptId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameIsNull() {
            addCriterion("initiateuser_name is null");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameIsNotNull() {
            addCriterion("initiateuser_name is not null");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameEqualTo(String value) {
            addCriterion("initiateuser_name =", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameNotEqualTo(String value) {
            addCriterion("initiateuser_name <>", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameGreaterThan(String value) {
            addCriterion("initiateuser_name >", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameGreaterThanOrEqualTo(String value) {
            addCriterion("initiateuser_name >=", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameLessThan(String value) {
            addCriterion("initiateuser_name <", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameLessThanOrEqualTo(String value) {
            addCriterion("initiateuser_name <=", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameLike(String value) {
            addCriterion("initiateuser_name like", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameNotLike(String value) {
            addCriterion("initiateuser_name not like", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameIn(List<String> values) {
            addCriterion("initiateuser_name in", values, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameNotIn(List<String> values) {
            addCriterion("initiateuser_name not in", values, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameBetween(String value1, String value2) {
            addCriterion("initiateuser_name between", value1, value2, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameNotBetween(String value1, String value2) {
            addCriterion("initiateuser_name not between", value1, value2, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdIsNull() {
            addCriterion("communicateuser_id is null");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdIsNotNull() {
            addCriterion("communicateuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdEqualTo(String value) {
            addCriterion("communicateuser_id =", value, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdNotEqualTo(String value) {
            addCriterion("communicateuser_id <>", value, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdGreaterThan(String value) {
            addCriterion("communicateuser_id >", value, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdGreaterThanOrEqualTo(String value) {
            addCriterion("communicateuser_id >=", value, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdLessThan(String value) {
            addCriterion("communicateuser_id <", value, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdLessThanOrEqualTo(String value) {
            addCriterion("communicateuser_id <=", value, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdLike(String value) {
            addCriterion("communicateuser_id like", value, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdNotLike(String value) {
            addCriterion("communicateuser_id not like", value, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdIn(List<String> values) {
            addCriterion("communicateuser_id in", values, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdNotIn(List<String> values) {
            addCriterion("communicateuser_id not in", values, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdBetween(String value1, String value2) {
            addCriterion("communicateuser_id between", value1, value2, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserIdNotBetween(String value1, String value2) {
            addCriterion("communicateuser_id not between", value1, value2, "communicateuserId");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameIsNull() {
            addCriterion("communicateuser_name is null");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameIsNotNull() {
            addCriterion("communicateuser_name is not null");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameEqualTo(String value) {
            addCriterion("communicateuser_name =", value, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameNotEqualTo(String value) {
            addCriterion("communicateuser_name <>", value, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameGreaterThan(String value) {
            addCriterion("communicateuser_name >", value, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameGreaterThanOrEqualTo(String value) {
            addCriterion("communicateuser_name >=", value, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameLessThan(String value) {
            addCriterion("communicateuser_name <", value, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameLessThanOrEqualTo(String value) {
            addCriterion("communicateuser_name <=", value, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameLike(String value) {
            addCriterion("communicateuser_name like", value, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameNotLike(String value) {
            addCriterion("communicateuser_name not like", value, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameIn(List<String> values) {
            addCriterion("communicateuser_name in", values, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameNotIn(List<String> values) {
            addCriterion("communicateuser_name not in", values, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameBetween(String value1, String value2) {
            addCriterion("communicateuser_name between", value1, value2, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andCommunicateuserNameNotBetween(String value1, String value2) {
            addCriterion("communicateuser_name not between", value1, value2, "communicateuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdIsNull() {
            addCriterion("inquiryuser_id is null");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdIsNotNull() {
            addCriterion("inquiryuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdEqualTo(String value) {
            addCriterion("inquiryuser_id =", value, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdNotEqualTo(String value) {
            addCriterion("inquiryuser_id <>", value, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdGreaterThan(String value) {
            addCriterion("inquiryuser_id >", value, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdGreaterThanOrEqualTo(String value) {
            addCriterion("inquiryuser_id >=", value, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdLessThan(String value) {
            addCriterion("inquiryuser_id <", value, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdLessThanOrEqualTo(String value) {
            addCriterion("inquiryuser_id <=", value, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdLike(String value) {
            addCriterion("inquiryuser_id like", value, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdNotLike(String value) {
            addCriterion("inquiryuser_id not like", value, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdIn(List<String> values) {
            addCriterion("inquiryuser_id in", values, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdNotIn(List<String> values) {
            addCriterion("inquiryuser_id not in", values, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdBetween(String value1, String value2) {
            addCriterion("inquiryuser_id between", value1, value2, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserIdNotBetween(String value1, String value2) {
            addCriterion("inquiryuser_id not between", value1, value2, "inquiryuserId");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameIsNull() {
            addCriterion("inquiryuser_name is null");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameIsNotNull() {
            addCriterion("inquiryuser_name is not null");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameEqualTo(String value) {
            addCriterion("inquiryuser_name =", value, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameNotEqualTo(String value) {
            addCriterion("inquiryuser_name <>", value, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameGreaterThan(String value) {
            addCriterion("inquiryuser_name >", value, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameGreaterThanOrEqualTo(String value) {
            addCriterion("inquiryuser_name >=", value, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameLessThan(String value) {
            addCriterion("inquiryuser_name <", value, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameLessThanOrEqualTo(String value) {
            addCriterion("inquiryuser_name <=", value, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameLike(String value) {
            addCriterion("inquiryuser_name like", value, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameNotLike(String value) {
            addCriterion("inquiryuser_name not like", value, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameIn(List<String> values) {
            addCriterion("inquiryuser_name in", values, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameNotIn(List<String> values) {
            addCriterion("inquiryuser_name not in", values, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameBetween(String value1, String value2) {
            addCriterion("inquiryuser_name between", value1, value2, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andInquiryuserNameNotBetween(String value1, String value2) {
            addCriterion("inquiryuser_name not between", value1, value2, "inquiryuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdIsNull() {
            addCriterion("evaluateuser_id is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdIsNotNull() {
            addCriterion("evaluateuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdEqualTo(String value) {
            addCriterion("evaluateuser_id =", value, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdNotEqualTo(String value) {
            addCriterion("evaluateuser_id <>", value, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdGreaterThan(String value) {
            addCriterion("evaluateuser_id >", value, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdGreaterThanOrEqualTo(String value) {
            addCriterion("evaluateuser_id >=", value, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdLessThan(String value) {
            addCriterion("evaluateuser_id <", value, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdLessThanOrEqualTo(String value) {
            addCriterion("evaluateuser_id <=", value, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdLike(String value) {
            addCriterion("evaluateuser_id like", value, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdNotLike(String value) {
            addCriterion("evaluateuser_id not like", value, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdIn(List<String> values) {
            addCriterion("evaluateuser_id in", values, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdNotIn(List<String> values) {
            addCriterion("evaluateuser_id not in", values, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdBetween(String value1, String value2) {
            addCriterion("evaluateuser_id between", value1, value2, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserIdNotBetween(String value1, String value2) {
            addCriterion("evaluateuser_id not between", value1, value2, "evaluateuserId");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameIsNull() {
            addCriterion("evaluateuser_name is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameIsNotNull() {
            addCriterion("evaluateuser_name is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameEqualTo(String value) {
            addCriterion("evaluateuser_name =", value, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameNotEqualTo(String value) {
            addCriterion("evaluateuser_name <>", value, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameGreaterThan(String value) {
            addCriterion("evaluateuser_name >", value, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameGreaterThanOrEqualTo(String value) {
            addCriterion("evaluateuser_name >=", value, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameLessThan(String value) {
            addCriterion("evaluateuser_name <", value, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameLessThanOrEqualTo(String value) {
            addCriterion("evaluateuser_name <=", value, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameLike(String value) {
            addCriterion("evaluateuser_name like", value, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameNotLike(String value) {
            addCriterion("evaluateuser_name not like", value, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameIn(List<String> values) {
            addCriterion("evaluateuser_name in", values, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameNotIn(List<String> values) {
            addCriterion("evaluateuser_name not in", values, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameBetween(String value1, String value2) {
            addCriterion("evaluateuser_name between", value1, value2, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andEvaluateuserNameNotBetween(String value1, String value2) {
            addCriterion("evaluateuser_name not between", value1, value2, "evaluateuserName");
            return (Criteria) this;
        }

        public Criteria andAudituserIdIsNull() {
            addCriterion("audituser_id is null");
            return (Criteria) this;
        }

        public Criteria andAudituserIdIsNotNull() {
            addCriterion("audituser_id is not null");
            return (Criteria) this;
        }

        public Criteria andAudituserIdEqualTo(String value) {
            addCriterion("audituser_id =", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdNotEqualTo(String value) {
            addCriterion("audituser_id <>", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdGreaterThan(String value) {
            addCriterion("audituser_id >", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdGreaterThanOrEqualTo(String value) {
            addCriterion("audituser_id >=", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdLessThan(String value) {
            addCriterion("audituser_id <", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdLessThanOrEqualTo(String value) {
            addCriterion("audituser_id <=", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdLike(String value) {
            addCriterion("audituser_id like", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdNotLike(String value) {
            addCriterion("audituser_id not like", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdIn(List<String> values) {
            addCriterion("audituser_id in", values, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdNotIn(List<String> values) {
            addCriterion("audituser_id not in", values, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdBetween(String value1, String value2) {
            addCriterion("audituser_id between", value1, value2, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdNotBetween(String value1, String value2) {
            addCriterion("audituser_id not between", value1, value2, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserNameIsNull() {
            addCriterion("audituser_name is null");
            return (Criteria) this;
        }

        public Criteria andAudituserNameIsNotNull() {
            addCriterion("audituser_name is not null");
            return (Criteria) this;
        }

        public Criteria andAudituserNameEqualTo(String value) {
            addCriterion("audituser_name =", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameNotEqualTo(String value) {
            addCriterion("audituser_name <>", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameGreaterThan(String value) {
            addCriterion("audituser_name >", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameGreaterThanOrEqualTo(String value) {
            addCriterion("audituser_name >=", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameLessThan(String value) {
            addCriterion("audituser_name <", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameLessThanOrEqualTo(String value) {
            addCriterion("audituser_name <=", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameLike(String value) {
            addCriterion("audituser_name like", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameNotLike(String value) {
            addCriterion("audituser_name not like", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameIn(List<String> values) {
            addCriterion("audituser_name in", values, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameNotIn(List<String> values) {
            addCriterion("audituser_name not in", values, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameBetween(String value1, String value2) {
            addCriterion("audituser_name between", value1, value2, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameNotBetween(String value1, String value2) {
            addCriterion("audituser_name not between", value1, value2, "audituserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdIsNull() {
            addCriterion("decisionuser_id is null");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdIsNotNull() {
            addCriterion("decisionuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdEqualTo(String value) {
            addCriterion("decisionuser_id =", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdNotEqualTo(String value) {
            addCriterion("decisionuser_id <>", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdGreaterThan(String value) {
            addCriterion("decisionuser_id >", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdGreaterThanOrEqualTo(String value) {
            addCriterion("decisionuser_id >=", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdLessThan(String value) {
            addCriterion("decisionuser_id <", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdLessThanOrEqualTo(String value) {
            addCriterion("decisionuser_id <=", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdLike(String value) {
            addCriterion("decisionuser_id like", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdNotLike(String value) {
            addCriterion("decisionuser_id not like", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdIn(List<String> values) {
            addCriterion("decisionuser_id in", values, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdNotIn(List<String> values) {
            addCriterion("decisionuser_id not in", values, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdBetween(String value1, String value2) {
            addCriterion("decisionuser_id between", value1, value2, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdNotBetween(String value1, String value2) {
            addCriterion("decisionuser_id not between", value1, value2, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameIsNull() {
            addCriterion("decisionuser_name is null");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameIsNotNull() {
            addCriterion("decisionuser_name is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameEqualTo(String value) {
            addCriterion("decisionuser_name =", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameNotEqualTo(String value) {
            addCriterion("decisionuser_name <>", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameGreaterThan(String value) {
            addCriterion("decisionuser_name >", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameGreaterThanOrEqualTo(String value) {
            addCriterion("decisionuser_name >=", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameLessThan(String value) {
            addCriterion("decisionuser_name <", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameLessThanOrEqualTo(String value) {
            addCriterion("decisionuser_name <=", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameLike(String value) {
            addCriterion("decisionuser_name like", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameNotLike(String value) {
            addCriterion("decisionuser_name not like", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameIn(List<String> values) {
            addCriterion("decisionuser_name in", values, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameNotIn(List<String> values) {
            addCriterion("decisionuser_name not in", values, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameBetween(String value1, String value2) {
            addCriterion("decisionuser_name between", value1, value2, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameNotBetween(String value1, String value2) {
            addCriterion("decisionuser_name not between", value1, value2, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeIsNull() {
            addCriterion("initiate_time is null");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeIsNotNull() {
            addCriterion("initiate_time is not null");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeEqualTo(Date value) {
            addCriterion("initiate_time =", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeNotEqualTo(Date value) {
            addCriterion("initiate_time <>", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeGreaterThan(Date value) {
            addCriterion("initiate_time >", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("initiate_time >=", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeLessThan(Date value) {
            addCriterion("initiate_time <", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeLessThanOrEqualTo(Date value) {
            addCriterion("initiate_time <=", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeIn(List<Date> values) {
            addCriterion("initiate_time in", values, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeNotIn(List<Date> values) {
            addCriterion("initiate_time not in", values, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeBetween(Date value1, Date value2) {
            addCriterion("initiate_time between", value1, value2, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeNotBetween(Date value1, Date value2) {
            addCriterion("initiate_time not between", value1, value2, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeIsNull() {
            addCriterion("communicate_time is null");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeIsNotNull() {
            addCriterion("communicate_time is not null");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeEqualTo(Date value) {
            addCriterion("communicate_time =", value, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeNotEqualTo(Date value) {
            addCriterion("communicate_time <>", value, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeGreaterThan(Date value) {
            addCriterion("communicate_time >", value, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("communicate_time >=", value, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeLessThan(Date value) {
            addCriterion("communicate_time <", value, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeLessThanOrEqualTo(Date value) {
            addCriterion("communicate_time <=", value, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeIn(List<Date> values) {
            addCriterion("communicate_time in", values, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeNotIn(List<Date> values) {
            addCriterion("communicate_time not in", values, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeBetween(Date value1, Date value2) {
            addCriterion("communicate_time between", value1, value2, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andCommunicateTimeNotBetween(Date value1, Date value2) {
            addCriterion("communicate_time not between", value1, value2, "communicateTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeIsNull() {
            addCriterion("inquiry_time is null");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeIsNotNull() {
            addCriterion("inquiry_time is not null");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeEqualTo(Date value) {
            addCriterion("inquiry_time =", value, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeNotEqualTo(Date value) {
            addCriterion("inquiry_time <>", value, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeGreaterThan(Date value) {
            addCriterion("inquiry_time >", value, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("inquiry_time >=", value, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeLessThan(Date value) {
            addCriterion("inquiry_time <", value, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeLessThanOrEqualTo(Date value) {
            addCriterion("inquiry_time <=", value, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeIn(List<Date> values) {
            addCriterion("inquiry_time in", values, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeNotIn(List<Date> values) {
            addCriterion("inquiry_time not in", values, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeBetween(Date value1, Date value2) {
            addCriterion("inquiry_time between", value1, value2, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andInquiryTimeNotBetween(Date value1, Date value2) {
            addCriterion("inquiry_time not between", value1, value2, "inquiryTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeIsNull() {
            addCriterion("evaluate_time is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeIsNotNull() {
            addCriterion("evaluate_time is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeEqualTo(Date value) {
            addCriterion("evaluate_time =", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeNotEqualTo(Date value) {
            addCriterion("evaluate_time <>", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeGreaterThan(Date value) {
            addCriterion("evaluate_time >", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("evaluate_time >=", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeLessThan(Date value) {
            addCriterion("evaluate_time <", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeLessThanOrEqualTo(Date value) {
            addCriterion("evaluate_time <=", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeIn(List<Date> values) {
            addCriterion("evaluate_time in", values, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeNotIn(List<Date> values) {
            addCriterion("evaluate_time not in", values, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeBetween(Date value1, Date value2) {
            addCriterion("evaluate_time between", value1, value2, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeNotBetween(Date value1, Date value2) {
            addCriterion("evaluate_time not between", value1, value2, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeIsNull() {
            addCriterion("decision_time is null");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeIsNotNull() {
            addCriterion("decision_time is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeEqualTo(Date value) {
            addCriterion("decision_time =", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeNotEqualTo(Date value) {
            addCriterion("decision_time <>", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeGreaterThan(Date value) {
            addCriterion("decision_time >", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("decision_time >=", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeLessThan(Date value) {
            addCriterion("decision_time <", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeLessThanOrEqualTo(Date value) {
            addCriterion("decision_time <=", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeIn(List<Date> values) {
            addCriterion("decision_time in", values, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeNotIn(List<Date> values) {
            addCriterion("decision_time not in", values, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeBetween(Date value1, Date value2) {
            addCriterion("decision_time between", value1, value2, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeNotBetween(Date value1, Date value2) {
            addCriterion("decision_time not between", value1, value2, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceIsNull() {
            addCriterion("inquiry_price is null");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceIsNotNull() {
            addCriterion("inquiry_price is not null");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceEqualTo(BigDecimal value) {
            addCriterion("inquiry_price =", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceNotEqualTo(BigDecimal value) {
            addCriterion("inquiry_price <>", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceGreaterThan(BigDecimal value) {
            addCriterion("inquiry_price >", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("inquiry_price >=", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceLessThan(BigDecimal value) {
            addCriterion("inquiry_price <", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("inquiry_price <=", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceIn(List<BigDecimal> values) {
            addCriterion("inquiry_price in", values, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceNotIn(List<BigDecimal> values) {
            addCriterion("inquiry_price not in", values, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inquiry_price between", value1, value2, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inquiry_price not between", value1, value2, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkIsNull() {
            addCriterion("initiate_remark is null");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkIsNotNull() {
            addCriterion("initiate_remark is not null");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkEqualTo(String value) {
            addCriterion("initiate_remark =", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkNotEqualTo(String value) {
            addCriterion("initiate_remark <>", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkGreaterThan(String value) {
            addCriterion("initiate_remark >", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("initiate_remark >=", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkLessThan(String value) {
            addCriterion("initiate_remark <", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkLessThanOrEqualTo(String value) {
            addCriterion("initiate_remark <=", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkLike(String value) {
            addCriterion("initiate_remark like", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkNotLike(String value) {
            addCriterion("initiate_remark not like", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkIn(List<String> values) {
            addCriterion("initiate_remark in", values, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkNotIn(List<String> values) {
            addCriterion("initiate_remark not in", values, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkBetween(String value1, String value2) {
            addCriterion("initiate_remark between", value1, value2, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkNotBetween(String value1, String value2) {
            addCriterion("initiate_remark not between", value1, value2, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkIsNull() {
            addCriterion("communicate_remark is null");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkIsNotNull() {
            addCriterion("communicate_remark is not null");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkEqualTo(String value) {
            addCriterion("communicate_remark =", value, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkNotEqualTo(String value) {
            addCriterion("communicate_remark <>", value, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkGreaterThan(String value) {
            addCriterion("communicate_remark >", value, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("communicate_remark >=", value, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkLessThan(String value) {
            addCriterion("communicate_remark <", value, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkLessThanOrEqualTo(String value) {
            addCriterion("communicate_remark <=", value, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkLike(String value) {
            addCriterion("communicate_remark like", value, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkNotLike(String value) {
            addCriterion("communicate_remark not like", value, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkIn(List<String> values) {
            addCriterion("communicate_remark in", values, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkNotIn(List<String> values) {
            addCriterion("communicate_remark not in", values, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkBetween(String value1, String value2) {
            addCriterion("communicate_remark between", value1, value2, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andCommunicateRemarkNotBetween(String value1, String value2) {
            addCriterion("communicate_remark not between", value1, value2, "communicateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkIsNull() {
            addCriterion("evaluate_remark is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkIsNotNull() {
            addCriterion("evaluate_remark is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkEqualTo(String value) {
            addCriterion("evaluate_remark =", value, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkNotEqualTo(String value) {
            addCriterion("evaluate_remark <>", value, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkGreaterThan(String value) {
            addCriterion("evaluate_remark >", value, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("evaluate_remark >=", value, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkLessThan(String value) {
            addCriterion("evaluate_remark <", value, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkLessThanOrEqualTo(String value) {
            addCriterion("evaluate_remark <=", value, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkLike(String value) {
            addCriterion("evaluate_remark like", value, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkNotLike(String value) {
            addCriterion("evaluate_remark not like", value, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkIn(List<String> values) {
            addCriterion("evaluate_remark in", values, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkNotIn(List<String> values) {
            addCriterion("evaluate_remark not in", values, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkBetween(String value1, String value2) {
            addCriterion("evaluate_remark between", value1, value2, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andEvaluateRemarkNotBetween(String value1, String value2) {
            addCriterion("evaluate_remark not between", value1, value2, "evaluateRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIsNull() {
            addCriterion("audit_remark is null");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIsNotNull() {
            addCriterion("audit_remark is not null");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkEqualTo(String value) {
            addCriterion("audit_remark =", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotEqualTo(String value) {
            addCriterion("audit_remark <>", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkGreaterThan(String value) {
            addCriterion("audit_remark >", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("audit_remark >=", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLessThan(String value) {
            addCriterion("audit_remark <", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLessThanOrEqualTo(String value) {
            addCriterion("audit_remark <=", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLike(String value) {
            addCriterion("audit_remark like", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotLike(String value) {
            addCriterion("audit_remark not like", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIn(List<String> values) {
            addCriterion("audit_remark in", values, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotIn(List<String> values) {
            addCriterion("audit_remark not in", values, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkBetween(String value1, String value2) {
            addCriterion("audit_remark between", value1, value2, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotBetween(String value1, String value2) {
            addCriterion("audit_remark not between", value1, value2, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andStepIsNull() {
            addCriterion("step is null");
            return (Criteria) this;
        }

        public Criteria andStepIsNotNull() {
            addCriterion("step is not null");
            return (Criteria) this;
        }

        public Criteria andStepEqualTo(Integer value) {
            addCriterion("step =", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotEqualTo(Integer value) {
            addCriterion("step <>", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThan(Integer value) {
            addCriterion("step >", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThanOrEqualTo(Integer value) {
            addCriterion("step >=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThan(Integer value) {
            addCriterion("step <", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThanOrEqualTo(Integer value) {
            addCriterion("step <=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepIn(List<Integer> values) {
            addCriterion("step in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotIn(List<Integer> values) {
            addCriterion("step not in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepBetween(Integer value1, Integer value2) {
            addCriterion("step between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotBetween(Integer value1, Integer value2) {
            addCriterion("step not between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultIsNull() {
            addCriterion("evaluate_result is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultIsNotNull() {
            addCriterion("evaluate_result is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultEqualTo(Integer value) {
            addCriterion("evaluate_result =", value, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultNotEqualTo(Integer value) {
            addCriterion("evaluate_result <>", value, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultGreaterThan(Integer value) {
            addCriterion("evaluate_result >", value, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("evaluate_result >=", value, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultLessThan(Integer value) {
            addCriterion("evaluate_result <", value, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultLessThanOrEqualTo(Integer value) {
            addCriterion("evaluate_result <=", value, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultIn(List<Integer> values) {
            addCriterion("evaluate_result in", values, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultNotIn(List<Integer> values) {
            addCriterion("evaluate_result not in", values, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultBetween(Integer value1, Integer value2) {
            addCriterion("evaluate_result between", value1, value2, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andEvaluateResultNotBetween(Integer value1, Integer value2) {
            addCriterion("evaluate_result not between", value1, value2, "evaluateResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultIsNull() {
            addCriterion("audit_result is null");
            return (Criteria) this;
        }

        public Criteria andAuditResultIsNotNull() {
            addCriterion("audit_result is not null");
            return (Criteria) this;
        }

        public Criteria andAuditResultEqualTo(Integer value) {
            addCriterion("audit_result =", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotEqualTo(Integer value) {
            addCriterion("audit_result <>", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultGreaterThan(Integer value) {
            addCriterion("audit_result >", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_result >=", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultLessThan(Integer value) {
            addCriterion("audit_result <", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultLessThanOrEqualTo(Integer value) {
            addCriterion("audit_result <=", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultIn(List<Integer> values) {
            addCriterion("audit_result in", values, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotIn(List<Integer> values) {
            addCriterion("audit_result not in", values, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultBetween(Integer value1, Integer value2) {
            addCriterion("audit_result between", value1, value2, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_result not between", value1, value2, "auditResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultIsNull() {
            addCriterion("decision_result is null");
            return (Criteria) this;
        }

        public Criteria andDecisionResultIsNotNull() {
            addCriterion("decision_result is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionResultEqualTo(Integer value) {
            addCriterion("decision_result =", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultNotEqualTo(Integer value) {
            addCriterion("decision_result <>", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultGreaterThan(Integer value) {
            addCriterion("decision_result >", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("decision_result >=", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultLessThan(Integer value) {
            addCriterion("decision_result <", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultLessThanOrEqualTo(Integer value) {
            addCriterion("decision_result <=", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultIn(List<Integer> values) {
            addCriterion("decision_result in", values, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultNotIn(List<Integer> values) {
            addCriterion("decision_result not in", values, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultBetween(Integer value1, Integer value2) {
            addCriterion("decision_result between", value1, value2, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultNotBetween(Integer value1, Integer value2) {
            addCriterion("decision_result not between", value1, value2, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andLifeStatusIsNull() {
            addCriterion("life_status is null");
            return (Criteria) this;
        }

        public Criteria andLifeStatusIsNotNull() {
            addCriterion("life_status is not null");
            return (Criteria) this;
        }

        public Criteria andLifeStatusEqualTo(Integer value) {
            addCriterion("life_status =", value, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andLifeStatusNotEqualTo(Integer value) {
            addCriterion("life_status <>", value, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andLifeStatusGreaterThan(Integer value) {
            addCriterion("life_status >", value, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andLifeStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("life_status >=", value, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andLifeStatusLessThan(Integer value) {
            addCriterion("life_status <", value, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andLifeStatusLessThanOrEqualTo(Integer value) {
            addCriterion("life_status <=", value, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andLifeStatusIn(List<Integer> values) {
            addCriterion("life_status in", values, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andLifeStatusNotIn(List<Integer> values) {
            addCriterion("life_status not in", values, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andLifeStatusBetween(Integer value1, Integer value2) {
            addCriterion("life_status between", value1, value2, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andLifeStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("life_status not between", value1, value2, "lifeStatus");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：inq_inquiry_order
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 询价申请单
     * Criterion
     * 数据库表：inq_inquiry_order
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}