package com.ddsh.util.service.api.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class InqInquiryOrder implements Serializable {
    /**
     * 主键ID
     * 表字段 : inq_inquiry_order.id
     */
    private String id;

    /**
     * 编码
     * 表字段 : inq_inquiry_order.code
     */
    private String code;

    /**
     * 名称
     * 表字段 : inq_inquiry_order.name
     */
    private String name;

    /**
     * 使用部门名称
     * 表字段 : inq_inquiry_order.use_dep_name
     */
    private String useDepName;

    /**
     * 使用部门id
     * 表字段 : inq_inquiry_order.use_dep_id
     */
    private String useDepId;

    /**
     * 询价发起人
     * 表字段 : inq_inquiry_order.initiateuser_id
     */
    private String initiateuserId;

    /**
     * 询价部门
     * 表字段 : inq_inquiry_order.initiatedept_id
     */
    private String initiatedeptId;

    /**
     * 询价发起人姓名
     * 表字段 : inq_inquiry_order.initiateuser_name
     */
    private String initiateuserName;

    /**
     * 详情沟通人
     * 表字段 : inq_inquiry_order.communicateuser_id
     */
    private String communicateuserId;

    /**
     * 详情沟通人姓名
     * 表字段 : inq_inquiry_order.communicateuser_name
     */
    private String communicateuserName;

    /**
     * 询价人
     * 表字段 : inq_inquiry_order.inquiryuser_id
     */
    private String inquiryuserId;

    /**
     * 询价人姓名
     * 表字段 : inq_inquiry_order.inquiryuser_name
     */
    private String inquiryuserName;

    /**
     * 现场评估人
     * 表字段 : inq_inquiry_order.evaluateuser_id
     */
    private String evaluateuserId;

    /**
     * 现场评估人姓名
     * 表字段 : inq_inquiry_order.evaluateuser_name
     */
    private String evaluateuserName;

    /**
     * 评估审核人
     * 表字段 : inq_inquiry_order.audituser_id
     */
    private String audituserId;

    /**
     * 评估审核人姓名
     * 表字段 : inq_inquiry_order.audituser_name
     */
    private String audituserName;

    /**
     * 决策人
     * 表字段 : inq_inquiry_order.decisionuser_id
     */
    private String decisionuserId;

    /**
     * 决策人姓名
     * 表字段 : inq_inquiry_order.decisionuser_name
     */
    private String decisionuserName;

    /**
     * 询价发起时间
     * 表字段 : inq_inquiry_order.initiate_time
     */
    private Date initiateTime;

    /**
     * 详情沟通时间
     * 表字段 : inq_inquiry_order.communicate_time
     */
    private Date communicateTime;

    /**
     * 询价时间
     * 表字段 : inq_inquiry_order.inquiry_time
     */
    private Date inquiryTime;

    /**
     * 现场评估时间
     * 表字段 : inq_inquiry_order.evaluate_time
     */
    private Date evaluateTime;

    /**
     * 评估审核时间
     * 表字段 : inq_inquiry_order.audit_time
     */
    private Date auditTime;

    /**
     * 决策时间
     * 表字段 : inq_inquiry_order.decision_time
     */
    private Date decisionTime;

    /**
     * 询价总价
     * 表字段 : inq_inquiry_order.inquiry_price
     */
    private BigDecimal inquiryPrice;

    /**
     * 询价说明，询价发起时填写
     * 表字段 : inq_inquiry_order.initiate_remark
     */
    private String initiateRemark;

    /**
     * 询价补充说明，详情沟通时填写
     * 表字段 : inq_inquiry_order.communicate_remark
     */
    private String communicateRemark;

    /**
     * 评估说明，现场评估后填写
     * 表字段 : inq_inquiry_order.evaluate_remark
     */
    private String evaluateRemark;

    /**
     * 审核说明，评估审核时填写
     * 表字段 : inq_inquiry_order.audit_remark
     */
    private String auditRemark;

    /**
     * 询价单所处节点：1待沟通2待询价3待评估4待审核5待决策6已完成
     * 表字段 : inq_inquiry_order.step
     */
    private Integer step;

    /**
     * 现场评估结论：1通过0不通过
     * 表字段 : inq_inquiry_order.evaluate_result
     */
    private Integer evaluateResult;

    /**
     * 评估审核结论：1通过0不通过
     * 表字段 : inq_inquiry_order.audit_result
     */
    private Integer auditResult;

    /**
     * 采购决策结论：1采购0不采购
     * 表字段 : inq_inquiry_order.decision_result
     */
    private Integer decisionResult;

    /**
     * 生命周期：1有效0失效, 从发起时间起一个月内的询价单置为失效，询价单不可再改变状态。采购、不采购均为已完成
     * 表字段 : inq_inquiry_order.life_status
     */
    private Integer lifeStatus;

    /**
     * 状态：1有效,0删除,-1草稿, 被删除的询价单置为已删除
     * 表字段 : inq_inquiry_order.status
     */
    private Integer status;

    /**
     * 更新时间
     * 表字段 : inq_inquiry_order.update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inq_inquiry_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    private List<InqInquiryOrderGoods> inqInquiryOrderGoodss;

    /**
     * 获取 主键ID 字段:inq_inquiry_order.id
     *
     * @return inq_inquiry_order.id, 主键ID
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 主键ID 字段:inq_inquiry_order.id
     *
     * @param id the value for inq_inquiry_order.id, 主键ID
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 编码 字段:inq_inquiry_order.code
     *
     * @return inq_inquiry_order.code, 编码
     */
    public String getCode() {
        return code;
    }

    /**
     * 设置 编码 字段:inq_inquiry_order.code
     *
     * @param code the value for inq_inquiry_order.code, 编码
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * 获取 名称 字段:inq_inquiry_order.name
     *
     * @return inq_inquiry_order.name, 名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 名称 字段:inq_inquiry_order.name
     *
     * @param name the value for inq_inquiry_order.name, 名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 使用部门名称 字段:inq_inquiry_order.use_dep_name
     *
     * @return inq_inquiry_order.use_dep_name, 使用部门名称
     */
    public String getUseDepName() {
        return useDepName;
    }

    /**
     * 设置 使用部门名称 字段:inq_inquiry_order.use_dep_name
     *
     * @param useDepName the value for inq_inquiry_order.use_dep_name, 使用部门名称
     */
    public void setUseDepName(String useDepName) {
        this.useDepName = useDepName == null ? null : useDepName.trim();
    }

    /**
     * 获取 使用部门id 字段:inq_inquiry_order.use_dep_id
     *
     * @return inq_inquiry_order.use_dep_id, 使用部门id
     */
    public String getUseDepId() {
        return useDepId;
    }

    /**
     * 设置 使用部门id 字段:inq_inquiry_order.use_dep_id
     *
     * @param useDepId the value for inq_inquiry_order.use_dep_id, 使用部门id
     */
    public void setUseDepId(String useDepId) {
        this.useDepId = useDepId == null ? null : useDepId.trim();
    }

    /**
     * 获取 询价发起人 字段:inq_inquiry_order.initiateuser_id
     *
     * @return inq_inquiry_order.initiateuser_id, 询价发起人
     */
    public String getInitiateuserId() {
        return initiateuserId;
    }

    /**
     * 设置 询价发起人 字段:inq_inquiry_order.initiateuser_id
     *
     * @param initiateuserId the value for inq_inquiry_order.initiateuser_id, 询价发起人
     */
    public void setInitiateuserId(String initiateuserId) {
        this.initiateuserId = initiateuserId == null ? null : initiateuserId.trim();
    }

    /**
     * 获取 询价部门 字段:inq_inquiry_order.initiatedept_id
     *
     * @return inq_inquiry_order.initiatedept_id, 询价部门
     */
    public String getInitiatedeptId() {
        return initiatedeptId;
    }

    /**
     * 设置 询价部门 字段:inq_inquiry_order.initiatedept_id
     *
     * @param initiatedeptId the value for inq_inquiry_order.initiatedept_id, 询价部门
     */
    public void setInitiatedeptId(String initiatedeptId) {
        this.initiatedeptId = initiatedeptId == null ? null : initiatedeptId.trim();
    }

    /**
     * 获取 询价发起人姓名 字段:inq_inquiry_order.initiateuser_name
     *
     * @return inq_inquiry_order.initiateuser_name, 询价发起人姓名
     */
    public String getInitiateuserName() {
        return initiateuserName;
    }

    /**
     * 设置 询价发起人姓名 字段:inq_inquiry_order.initiateuser_name
     *
     * @param initiateuserName the value for inq_inquiry_order.initiateuser_name, 询价发起人姓名
     */
    public void setInitiateuserName(String initiateuserName) {
        this.initiateuserName = initiateuserName == null ? null : initiateuserName.trim();
    }

    /**
     * 获取 详情沟通人 字段:inq_inquiry_order.communicateuser_id
     *
     * @return inq_inquiry_order.communicateuser_id, 详情沟通人
     */
    public String getCommunicateuserId() {
        return communicateuserId;
    }

    /**
     * 设置 详情沟通人 字段:inq_inquiry_order.communicateuser_id
     *
     * @param communicateuserId the value for inq_inquiry_order.communicateuser_id, 详情沟通人
     */
    public void setCommunicateuserId(String communicateuserId) {
        this.communicateuserId = communicateuserId == null ? null : communicateuserId.trim();
    }

    /**
     * 获取 详情沟通人姓名 字段:inq_inquiry_order.communicateuser_name
     *
     * @return inq_inquiry_order.communicateuser_name, 详情沟通人姓名
     */
    public String getCommunicateuserName() {
        return communicateuserName;
    }

    /**
     * 设置 详情沟通人姓名 字段:inq_inquiry_order.communicateuser_name
     *
     * @param communicateuserName the value for inq_inquiry_order.communicateuser_name, 详情沟通人姓名
     */
    public void setCommunicateuserName(String communicateuserName) {
        this.communicateuserName = communicateuserName == null ? null : communicateuserName.trim();
    }

    /**
     * 获取 询价人 字段:inq_inquiry_order.inquiryuser_id
     *
     * @return inq_inquiry_order.inquiryuser_id, 询价人
     */
    public String getInquiryuserId() {
        return inquiryuserId;
    }

    /**
     * 设置 询价人 字段:inq_inquiry_order.inquiryuser_id
     *
     * @param inquiryuserId the value for inq_inquiry_order.inquiryuser_id, 询价人
     */
    public void setInquiryuserId(String inquiryuserId) {
        this.inquiryuserId = inquiryuserId == null ? null : inquiryuserId.trim();
    }

    /**
     * 获取 询价人姓名 字段:inq_inquiry_order.inquiryuser_name
     *
     * @return inq_inquiry_order.inquiryuser_name, 询价人姓名
     */
    public String getInquiryuserName() {
        return inquiryuserName;
    }

    /**
     * 设置 询价人姓名 字段:inq_inquiry_order.inquiryuser_name
     *
     * @param inquiryuserName the value for inq_inquiry_order.inquiryuser_name, 询价人姓名
     */
    public void setInquiryuserName(String inquiryuserName) {
        this.inquiryuserName = inquiryuserName == null ? null : inquiryuserName.trim();
    }

    /**
     * 获取 现场评估人 字段:inq_inquiry_order.evaluateuser_id
     *
     * @return inq_inquiry_order.evaluateuser_id, 现场评估人
     */
    public String getEvaluateuserId() {
        return evaluateuserId;
    }

    /**
     * 设置 现场评估人 字段:inq_inquiry_order.evaluateuser_id
     *
     * @param evaluateuserId the value for inq_inquiry_order.evaluateuser_id, 现场评估人
     */
    public void setEvaluateuserId(String evaluateuserId) {
        this.evaluateuserId = evaluateuserId == null ? null : evaluateuserId.trim();
    }

    /**
     * 获取 现场评估人姓名 字段:inq_inquiry_order.evaluateuser_name
     *
     * @return inq_inquiry_order.evaluateuser_name, 现场评估人姓名
     */
    public String getEvaluateuserName() {
        return evaluateuserName;
    }

    /**
     * 设置 现场评估人姓名 字段:inq_inquiry_order.evaluateuser_name
     *
     * @param evaluateuserName the value for inq_inquiry_order.evaluateuser_name, 现场评估人姓名
     */
    public void setEvaluateuserName(String evaluateuserName) {
        this.evaluateuserName = evaluateuserName == null ? null : evaluateuserName.trim();
    }

    /**
     * 获取 评估审核人 字段:inq_inquiry_order.audituser_id
     *
     * @return inq_inquiry_order.audituser_id, 评估审核人
     */
    public String getAudituserId() {
        return audituserId;
    }

    /**
     * 设置 评估审核人 字段:inq_inquiry_order.audituser_id
     *
     * @param audituserId the value for inq_inquiry_order.audituser_id, 评估审核人
     */
    public void setAudituserId(String audituserId) {
        this.audituserId = audituserId == null ? null : audituserId.trim();
    }

    /**
     * 获取 评估审核人姓名 字段:inq_inquiry_order.audituser_name
     *
     * @return inq_inquiry_order.audituser_name, 评估审核人姓名
     */
    public String getAudituserName() {
        return audituserName;
    }

    /**
     * 设置 评估审核人姓名 字段:inq_inquiry_order.audituser_name
     *
     * @param audituserName the value for inq_inquiry_order.audituser_name, 评估审核人姓名
     */
    public void setAudituserName(String audituserName) {
        this.audituserName = audituserName == null ? null : audituserName.trim();
    }

    /**
     * 获取 决策人 字段:inq_inquiry_order.decisionuser_id
     *
     * @return inq_inquiry_order.decisionuser_id, 决策人
     */
    public String getDecisionuserId() {
        return decisionuserId;
    }

    /**
     * 设置 决策人 字段:inq_inquiry_order.decisionuser_id
     *
     * @param decisionuserId the value for inq_inquiry_order.decisionuser_id, 决策人
     */
    public void setDecisionuserId(String decisionuserId) {
        this.decisionuserId = decisionuserId == null ? null : decisionuserId.trim();
    }

    /**
     * 获取 决策人姓名 字段:inq_inquiry_order.decisionuser_name
     *
     * @return inq_inquiry_order.decisionuser_name, 决策人姓名
     */
    public String getDecisionuserName() {
        return decisionuserName;
    }

    /**
     * 设置 决策人姓名 字段:inq_inquiry_order.decisionuser_name
     *
     * @param decisionuserName the value for inq_inquiry_order.decisionuser_name, 决策人姓名
     */
    public void setDecisionuserName(String decisionuserName) {
        this.decisionuserName = decisionuserName == null ? null : decisionuserName.trim();
    }

    /**
     * 获取 询价发起时间 字段:inq_inquiry_order.initiate_time
     *
     * @return inq_inquiry_order.initiate_time, 询价发起时间
     */
    public Date getInitiateTime() {
        return initiateTime;
    }

    /**
     * 设置 询价发起时间 字段:inq_inquiry_order.initiate_time
     *
     * @param initiateTime the value for inq_inquiry_order.initiate_time, 询价发起时间
     */
    public void setInitiateTime(Date initiateTime) {
        this.initiateTime = initiateTime;
    }

    /**
     * 获取 详情沟通时间 字段:inq_inquiry_order.communicate_time
     *
     * @return inq_inquiry_order.communicate_time, 详情沟通时间
     */
    public Date getCommunicateTime() {
        return communicateTime;
    }

    /**
     * 设置 详情沟通时间 字段:inq_inquiry_order.communicate_time
     *
     * @param communicateTime the value for inq_inquiry_order.communicate_time, 详情沟通时间
     */
    public void setCommunicateTime(Date communicateTime) {
        this.communicateTime = communicateTime;
    }

    /**
     * 获取 询价时间 字段:inq_inquiry_order.inquiry_time
     *
     * @return inq_inquiry_order.inquiry_time, 询价时间
     */
    public Date getInquiryTime() {
        return inquiryTime;
    }

    /**
     * 设置 询价时间 字段:inq_inquiry_order.inquiry_time
     *
     * @param inquiryTime the value for inq_inquiry_order.inquiry_time, 询价时间
     */
    public void setInquiryTime(Date inquiryTime) {
        this.inquiryTime = inquiryTime;
    }

    /**
     * 获取 现场评估时间 字段:inq_inquiry_order.evaluate_time
     *
     * @return inq_inquiry_order.evaluate_time, 现场评估时间
     */
    public Date getEvaluateTime() {
        return evaluateTime;
    }

    /**
     * 设置 现场评估时间 字段:inq_inquiry_order.evaluate_time
     *
     * @param evaluateTime the value for inq_inquiry_order.evaluate_time, 现场评估时间
     */
    public void setEvaluateTime(Date evaluateTime) {
        this.evaluateTime = evaluateTime;
    }

    /**
     * 获取 评估审核时间 字段:inq_inquiry_order.audit_time
     *
     * @return inq_inquiry_order.audit_time, 评估审核时间
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * 设置 评估审核时间 字段:inq_inquiry_order.audit_time
     *
     * @param auditTime the value for inq_inquiry_order.audit_time, 评估审核时间
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * 获取 决策时间 字段:inq_inquiry_order.decision_time
     *
     * @return inq_inquiry_order.decision_time, 决策时间
     */
    public Date getDecisionTime() {
        return decisionTime;
    }

    /**
     * 设置 决策时间 字段:inq_inquiry_order.decision_time
     *
     * @param decisionTime the value for inq_inquiry_order.decision_time, 决策时间
     */
    public void setDecisionTime(Date decisionTime) {
        this.decisionTime = decisionTime;
    }

    /**
     * 获取 询价总价 字段:inq_inquiry_order.inquiry_price
     *
     * @return inq_inquiry_order.inquiry_price, 询价总价
     */
    public BigDecimal getInquiryPrice() {
        return inquiryPrice;
    }

    /**
     * 设置 询价总价 字段:inq_inquiry_order.inquiry_price
     *
     * @param inquiryPrice the value for inq_inquiry_order.inquiry_price, 询价总价
     */
    public void setInquiryPrice(BigDecimal inquiryPrice) {
        this.inquiryPrice = inquiryPrice;
    }

    /**
     * 获取 询价说明，询价发起时填写 字段:inq_inquiry_order.initiate_remark
     *
     * @return inq_inquiry_order.initiate_remark, 询价说明，询价发起时填写
     */
    public String getInitiateRemark() {
        return initiateRemark;
    }

    /**
     * 设置 询价说明，询价发起时填写 字段:inq_inquiry_order.initiate_remark
     *
     * @param initiateRemark the value for inq_inquiry_order.initiate_remark, 询价说明，询价发起时填写
     */
    public void setInitiateRemark(String initiateRemark) {
        this.initiateRemark = initiateRemark == null ? null : initiateRemark.trim();
    }

    /**
     * 获取 询价补充说明，详情沟通时填写 字段:inq_inquiry_order.communicate_remark
     *
     * @return inq_inquiry_order.communicate_remark, 询价补充说明，详情沟通时填写
     */
    public String getCommunicateRemark() {
        return communicateRemark;
    }

    /**
     * 设置 询价补充说明，详情沟通时填写 字段:inq_inquiry_order.communicate_remark
     *
     * @param communicateRemark the value for inq_inquiry_order.communicate_remark, 询价补充说明，详情沟通时填写
     */
    public void setCommunicateRemark(String communicateRemark) {
        this.communicateRemark = communicateRemark == null ? null : communicateRemark.trim();
    }

    /**
     * 获取 评估说明，现场评估后填写 字段:inq_inquiry_order.evaluate_remark
     *
     * @return inq_inquiry_order.evaluate_remark, 评估说明，现场评估后填写
     */
    public String getEvaluateRemark() {
        return evaluateRemark;
    }

    /**
     * 设置 评估说明，现场评估后填写 字段:inq_inquiry_order.evaluate_remark
     *
     * @param evaluateRemark the value for inq_inquiry_order.evaluate_remark, 评估说明，现场评估后填写
     */
    public void setEvaluateRemark(String evaluateRemark) {
        this.evaluateRemark = evaluateRemark == null ? null : evaluateRemark.trim();
    }

    /**
     * 获取 审核说明，评估审核时填写 字段:inq_inquiry_order.audit_remark
     *
     * @return inq_inquiry_order.audit_remark, 审核说明，评估审核时填写
     */
    public String getAuditRemark() {
        return auditRemark;
    }

    /**
     * 设置 审核说明，评估审核时填写 字段:inq_inquiry_order.audit_remark
     *
     * @param auditRemark the value for inq_inquiry_order.audit_remark, 审核说明，评估审核时填写
     */
    public void setAuditRemark(String auditRemark) {
        this.auditRemark = auditRemark == null ? null : auditRemark.trim();
    }

    /**
     * 获取 询价单所处节点：1待沟通2待询价3待评估4待审核5待决策6已完成 字段:inq_inquiry_order.step
     *
     * @return inq_inquiry_order.step, 询价单所处节点：1待沟通2待询价3待评估4待审核5待决策6已完成
     */
    public Integer getStep() {
        return step;
    }

    /**
     * 设置 询价单所处节点：1待沟通2待询价3待评估4待审核5待决策6已完成 字段:inq_inquiry_order.step
     *
     * @param step the value for inq_inquiry_order.step, 询价单所处节点：1待沟通2待询价3待评估4待审核5待决策6已完成
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * 获取 现场评估结论：1通过0不通过 字段:inq_inquiry_order.evaluate_result
     *
     * @return inq_inquiry_order.evaluate_result, 现场评估结论：1通过0不通过
     */
    public Integer getEvaluateResult() {
        return evaluateResult;
    }

    /**
     * 设置 现场评估结论：1通过0不通过 字段:inq_inquiry_order.evaluate_result
     *
     * @param evaluateResult the value for inq_inquiry_order.evaluate_result, 现场评估结论：1通过0不通过
     */
    public void setEvaluateResult(Integer evaluateResult) {
        this.evaluateResult = evaluateResult;
    }

    /**
     * 获取 评估审核结论：1通过0不通过 字段:inq_inquiry_order.audit_result
     *
     * @return inq_inquiry_order.audit_result, 评估审核结论：1通过0不通过
     */
    public Integer getAuditResult() {
        return auditResult;
    }

    /**
     * 设置 评估审核结论：1通过0不通过 字段:inq_inquiry_order.audit_result
     *
     * @param auditResult the value for inq_inquiry_order.audit_result, 评估审核结论：1通过0不通过
     */
    public void setAuditResult(Integer auditResult) {
        this.auditResult = auditResult;
    }

    /**
     * 获取 采购决策结论：1采购0不采购 字段:inq_inquiry_order.decision_result
     *
     * @return inq_inquiry_order.decision_result, 采购决策结论：1采购0不采购
     */
    public Integer getDecisionResult() {
        return decisionResult;
    }

    /**
     * 设置 采购决策结论：1采购0不采购 字段:inq_inquiry_order.decision_result
     *
     * @param decisionResult the value for inq_inquiry_order.decision_result, 采购决策结论：1采购0不采购
     */
    public void setDecisionResult(Integer decisionResult) {
        this.decisionResult = decisionResult;
    }

    /**
     * 获取 生命周期：1有效0失效, 从发起时间起一个月内的询价单置为失效，询价单不可再改变状态。采购、不采购均为已完成 字段:inq_inquiry_order.life_status
     *
     * @return inq_inquiry_order.life_status, 生命周期：1有效0失效, 从发起时间起一个月内的询价单置为失效，询价单不可再改变状态。采购、不采购均为已完成
     */
    public Integer getLifeStatus() {
        return lifeStatus;
    }

    /**
     * 设置 生命周期：1有效0失效, 从发起时间起一个月内的询价单置为失效，询价单不可再改变状态。采购、不采购均为已完成 字段:inq_inquiry_order.life_status
     *
     * @param lifeStatus the value for inq_inquiry_order.life_status, 生命周期：1有效0失效, 从发起时间起一个月内的询价单置为失效，询价单不可再改变状态。采购、不采购均为已完成
     */
    public void setLifeStatus(Integer lifeStatus) {
        this.lifeStatus = lifeStatus;
    }

    /**
     * 获取 状态：1有效,0删除,-1草稿, 被删除的询价单置为已删除 字段:inq_inquiry_order.status
     *
     * @return inq_inquiry_order.status, 状态：1有效,0删除,-1草稿, 被删除的询价单置为已删除
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态：1有效,0删除,-1草稿, 被删除的询价单置为已删除 字段:inq_inquiry_order.status
     *
     * @param status the value for inq_inquiry_order.status, 状态：1有效,0删除,-1草稿, 被删除的询价单置为已删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 更新时间 字段:inq_inquiry_order.update_time
     *
     * @return inq_inquiry_order.update_time, 更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 更新时间 字段:inq_inquiry_order.update_time
     *
     * @param updateTime the value for inq_inquiry_order.update_time, 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * ,inq_inquiry_order
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", useDepName=").append(useDepName);
        sb.append(", useDepId=").append(useDepId);
        sb.append(", initiateuserId=").append(initiateuserId);
        sb.append(", initiatedeptId=").append(initiatedeptId);
        sb.append(", initiateuserName=").append(initiateuserName);
        sb.append(", communicateuserId=").append(communicateuserId);
        sb.append(", communicateuserName=").append(communicateuserName);
        sb.append(", inquiryuserId=").append(inquiryuserId);
        sb.append(", inquiryuserName=").append(inquiryuserName);
        sb.append(", evaluateuserId=").append(evaluateuserId);
        sb.append(", evaluateuserName=").append(evaluateuserName);
        sb.append(", audituserId=").append(audituserId);
        sb.append(", audituserName=").append(audituserName);
        sb.append(", decisionuserId=").append(decisionuserId);
        sb.append(", decisionuserName=").append(decisionuserName);
        sb.append(", initiateTime=").append(initiateTime);
        sb.append(", communicateTime=").append(communicateTime);
        sb.append(", inquiryTime=").append(inquiryTime);
        sb.append(", evaluateTime=").append(evaluateTime);
        sb.append(", auditTime=").append(auditTime);
        sb.append(", decisionTime=").append(decisionTime);
        sb.append(", inquiryPrice=").append(inquiryPrice);
        sb.append(", initiateRemark=").append(initiateRemark);
        sb.append(", communicateRemark=").append(communicateRemark);
        sb.append(", evaluateRemark=").append(evaluateRemark);
        sb.append(", auditRemark=").append(auditRemark);
        sb.append(", step=").append(step);
        sb.append(", evaluateResult=").append(evaluateResult);
        sb.append(", auditResult=").append(auditResult);
        sb.append(", decisionResult=").append(decisionResult);
        sb.append(", lifeStatus=").append(lifeStatus);
        sb.append(", status=").append(status);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public List<InqInquiryOrderGoods> getInqInquiryOrderGoodss() {
        return inqInquiryOrderGoodss;
    }

    public void setInqInquiryOrderGoodss(List<InqInquiryOrderGoods> inqInquiryOrderGoodss) {
        this.inqInquiryOrderGoodss=inqInquiryOrderGoodss;
    }
}