package com.ddsh.util.service.api.model;

import java.io.Serializable;
import java.util.Date;

public class PurPurchaseOrderHis implements Serializable {
    /**
     * id
     * 表字段 : pur_purchase_order_his.id
     */
    private String id;

    /**
     * 所属采购单
     * 表字段 : pur_purchase_order_his.purchase_id
     */
    private String purchaseId;

    /**
     * 操作用户id
     * 表字段 : pur_purchase_order_his.user_id
     */
    private String userId;

    /**
     * 操作用户名称
     * 表字段 : pur_purchase_order_his.user_name
     */
    private String userName;

    /**
     * 撤销前状态
     * 表字段 : pur_purchase_order_his.source_step
     */
    private Integer sourceStep;

    /**
     * 撤销后状态
     * 表字段 : pur_purchase_order_his.target_step
     */
    private Integer targetStep;

    /**
     * 撤销原因
     * 表字段 : pur_purchase_order_his.remark
     */
    private String remark;

    /**
     * 更新时间
     * 表字段 : pur_purchase_order_his.create_time
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_order_his
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 id 字段:pur_purchase_order_his.id
     *
     * @return pur_purchase_order_his.id, id
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 id 字段:pur_purchase_order_his.id
     *
     * @param id the value for pur_purchase_order_his.id, id
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 所属采购单 字段:pur_purchase_order_his.purchase_id
     *
     * @return pur_purchase_order_his.purchase_id, 所属采购单
     */
    public String getPurchaseId() {
        return purchaseId;
    }

    /**
     * 设置 所属采购单 字段:pur_purchase_order_his.purchase_id
     *
     * @param purchaseId the value for pur_purchase_order_his.purchase_id, 所属采购单
     */
    public void setPurchaseId(String purchaseId) {
        this.purchaseId = purchaseId == null ? null : purchaseId.trim();
    }

    /**
     * 获取 操作用户id 字段:pur_purchase_order_his.user_id
     *
     * @return pur_purchase_order_his.user_id, 操作用户id
     */
    public String getUserId() {
        return userId;
    }

    /**
     * 设置 操作用户id 字段:pur_purchase_order_his.user_id
     *
     * @param userId the value for pur_purchase_order_his.user_id, 操作用户id
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * 获取 操作用户名称 字段:pur_purchase_order_his.user_name
     *
     * @return pur_purchase_order_his.user_name, 操作用户名称
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 设置 操作用户名称 字段:pur_purchase_order_his.user_name
     *
     * @param userName the value for pur_purchase_order_his.user_name, 操作用户名称
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 获取 撤销前状态 字段:pur_purchase_order_his.source_step
     *
     * @return pur_purchase_order_his.source_step, 撤销前状态
     */
    public Integer getSourceStep() {
        return sourceStep;
    }

    /**
     * 设置 撤销前状态 字段:pur_purchase_order_his.source_step
     *
     * @param sourceStep the value for pur_purchase_order_his.source_step, 撤销前状态
     */
    public void setSourceStep(Integer sourceStep) {
        this.sourceStep = sourceStep;
    }

    /**
     * 获取 撤销后状态 字段:pur_purchase_order_his.target_step
     *
     * @return pur_purchase_order_his.target_step, 撤销后状态
     */
    public Integer getTargetStep() {
        return targetStep;
    }

    /**
     * 设置 撤销后状态 字段:pur_purchase_order_his.target_step
     *
     * @param targetStep the value for pur_purchase_order_his.target_step, 撤销后状态
     */
    public void setTargetStep(Integer targetStep) {
        this.targetStep = targetStep;
    }

    /**
     * 获取 撤销原因 字段:pur_purchase_order_his.remark
     *
     * @return pur_purchase_order_his.remark, 撤销原因
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 撤销原因 字段:pur_purchase_order_his.remark
     *
     * @param remark the value for pur_purchase_order_his.remark, 撤销原因
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取 更新时间 字段:pur_purchase_order_his.create_time
     *
     * @return pur_purchase_order_his.create_time, 更新时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 更新时间 字段:pur_purchase_order_his.create_time
     *
     * @param createTime the value for pur_purchase_order_his.create_time, 更新时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * ,pur_purchase_order_his
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", purchaseId=").append(purchaseId);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", sourceStep=").append(sourceStep);
        sb.append(", targetStep=").append(targetStep);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}