package com.ddsh.util.service.api.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PurPurchaseOrderGoods implements Serializable {
    /**
     * 主键ID
     * 表字段 : pur_purchase_order_goods.id
     */
    private String id;

    /**
     * 采购单与询价单关联ID
     * 表字段 : pur_purchase_order_goods.purchase_inquiry_id
     */
    private String purchaseInquiryId;

    /**
     * 物资ID
     * 表字段 : pur_purchase_order_goods.goods_id
     */
    private String goodsId;

    /**
     * 物资名称
     * 表字段 : pur_purchase_order_goods.name
     */
    private String name;

    /**
     * 编码
     * 表字段 : pur_purchase_order_goods.code
     */
    private String code;

    /**
     * 类型
     * 表字段 : pur_purchase_order_goods.type
     */
    private String type;

    /**
     * 品牌名称
     * 表字段 : pur_purchase_order_goods.brand
     */
    private String brand;

    /**
     * 颜色
     * 表字段 : pur_purchase_order_goods.colour
     */
    private String colour;

    /**
     * 单位
     * 表字段 : pur_purchase_order_goods.unit
     */
    private String unit;

    /**
     * 规格说明
     * 表字段 : pur_purchase_order_goods.norm
     */
    private String norm;

    /**
     * 备注
     * 表字段 : pur_purchase_order_goods.remark
     */
    private String remark;

    /**
     * 询价单价
     * 表字段 : pur_purchase_order_goods.unit_price
     */
    private BigDecimal unitPrice;

    /**
     * 实际采购单价
     * 表字段 : pur_purchase_order_goods.price
     */
    private BigDecimal price;

    /**
     * 询价数量
     * 表字段 : pur_purchase_order_goods.quantity
     */
    private Integer quantity;

    /**
     * 已入库数量
     * 表字段 : pur_purchase_order_goods.instore_num
     */
    private Integer instoreNum;

    /**
     * 供货商
     * 表字段 : pur_purchase_order_goods.supplier
     */
    private String supplier;

    /**
     * 预计到货时间
     * 表字段 : pur_purchase_order_goods.arrival_time
     */
    private Date arrivalTime;

    /**
     * 物资状态1为可用，0不可用
     * 表字段 : pur_purchase_order_goods.status
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_order_goods
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键ID 字段:pur_purchase_order_goods.id
     *
     * @return pur_purchase_order_goods.id, 主键ID
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 主键ID 字段:pur_purchase_order_goods.id
     *
     * @param id the value for pur_purchase_order_goods.id, 主键ID
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 采购单与询价单关联ID 字段:pur_purchase_order_goods.purchase_inquiry_id
     *
     * @return pur_purchase_order_goods.purchase_inquiry_id, 采购单与询价单关联ID
     */
    public String getPurchaseInquiryId() {
        return purchaseInquiryId;
    }

    /**
     * 设置 采购单与询价单关联ID 字段:pur_purchase_order_goods.purchase_inquiry_id
     *
     * @param purchaseInquiryId the value for pur_purchase_order_goods.purchase_inquiry_id, 采购单与询价单关联ID
     */
    public void setPurchaseInquiryId(String purchaseInquiryId) {
        this.purchaseInquiryId = purchaseInquiryId == null ? null : purchaseInquiryId.trim();
    }

    /**
     * 获取 物资ID 字段:pur_purchase_order_goods.goods_id
     *
     * @return pur_purchase_order_goods.goods_id, 物资ID
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * 设置 物资ID 字段:pur_purchase_order_goods.goods_id
     *
     * @param goodsId the value for pur_purchase_order_goods.goods_id, 物资ID
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * 获取 物资名称 字段:pur_purchase_order_goods.name
     *
     * @return pur_purchase_order_goods.name, 物资名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 物资名称 字段:pur_purchase_order_goods.name
     *
     * @param name the value for pur_purchase_order_goods.name, 物资名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 编码 字段:pur_purchase_order_goods.code
     *
     * @return pur_purchase_order_goods.code, 编码
     */
    public String getCode() {
        return code;
    }

    /**
     * 设置 编码 字段:pur_purchase_order_goods.code
     *
     * @param code the value for pur_purchase_order_goods.code, 编码
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * 获取 类型 字段:pur_purchase_order_goods.type
     *
     * @return pur_purchase_order_goods.type, 类型
     */
    public String getType() {
        return type;
    }

    /**
     * 设置 类型 字段:pur_purchase_order_goods.type
     *
     * @param type the value for pur_purchase_order_goods.type, 类型
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 获取 品牌名称 字段:pur_purchase_order_goods.brand
     *
     * @return pur_purchase_order_goods.brand, 品牌名称
     */
    public String getBrand() {
        return brand;
    }

    /**
     * 设置 品牌名称 字段:pur_purchase_order_goods.brand
     *
     * @param brand the value for pur_purchase_order_goods.brand, 品牌名称
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * 获取 颜色 字段:pur_purchase_order_goods.colour
     *
     * @return pur_purchase_order_goods.colour, 颜色
     */
    public String getColour() {
        return colour;
    }

    /**
     * 设置 颜色 字段:pur_purchase_order_goods.colour
     *
     * @param colour the value for pur_purchase_order_goods.colour, 颜色
     */
    public void setColour(String colour) {
        this.colour = colour == null ? null : colour.trim();
    }

    /**
     * 获取 单位 字段:pur_purchase_order_goods.unit
     *
     * @return pur_purchase_order_goods.unit, 单位
     */
    public String getUnit() {
        return unit;
    }

    /**
     * 设置 单位 字段:pur_purchase_order_goods.unit
     *
     * @param unit the value for pur_purchase_order_goods.unit, 单位
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * 获取 规格说明 字段:pur_purchase_order_goods.norm
     *
     * @return pur_purchase_order_goods.norm, 规格说明
     */
    public String getNorm() {
        return norm;
    }

    /**
     * 设置 规格说明 字段:pur_purchase_order_goods.norm
     *
     * @param norm the value for pur_purchase_order_goods.norm, 规格说明
     */
    public void setNorm(String norm) {
        this.norm = norm == null ? null : norm.trim();
    }

    /**
     * 获取 备注 字段:pur_purchase_order_goods.remark
     *
     * @return pur_purchase_order_goods.remark, 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 备注 字段:pur_purchase_order_goods.remark
     *
     * @param remark the value for pur_purchase_order_goods.remark, 备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取 询价单价 字段:pur_purchase_order_goods.unit_price
     *
     * @return pur_purchase_order_goods.unit_price, 询价单价
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * 设置 询价单价 字段:pur_purchase_order_goods.unit_price
     *
     * @param unitPrice the value for pur_purchase_order_goods.unit_price, 询价单价
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * 获取 实际采购单价 字段:pur_purchase_order_goods.price
     *
     * @return pur_purchase_order_goods.price, 实际采购单价
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * 设置 实际采购单价 字段:pur_purchase_order_goods.price
     *
     * @param price the value for pur_purchase_order_goods.price, 实际采购单价
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * 获取 询价数量 字段:pur_purchase_order_goods.quantity
     *
     * @return pur_purchase_order_goods.quantity, 询价数量
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * 设置 询价数量 字段:pur_purchase_order_goods.quantity
     *
     * @param quantity the value for pur_purchase_order_goods.quantity, 询价数量
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * 获取 已入库数量 字段:pur_purchase_order_goods.instore_num
     *
     * @return pur_purchase_order_goods.instore_num, 已入库数量
     */
    public Integer getInstoreNum() {
        return instoreNum;
    }

    /**
     * 设置 已入库数量 字段:pur_purchase_order_goods.instore_num
     *
     * @param instoreNum the value for pur_purchase_order_goods.instore_num, 已入库数量
     */
    public void setInstoreNum(Integer instoreNum) {
        this.instoreNum = instoreNum;
    }

    /**
     * 获取 供货商 字段:pur_purchase_order_goods.supplier
     *
     * @return pur_purchase_order_goods.supplier, 供货商
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * 设置 供货商 字段:pur_purchase_order_goods.supplier
     *
     * @param supplier the value for pur_purchase_order_goods.supplier, 供货商
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * 获取 预计到货时间 字段:pur_purchase_order_goods.arrival_time
     *
     * @return pur_purchase_order_goods.arrival_time, 预计到货时间
     */
    public Date getArrivalTime() {
        return arrivalTime;
    }

    /**
     * 设置 预计到货时间 字段:pur_purchase_order_goods.arrival_time
     *
     * @param arrivalTime the value for pur_purchase_order_goods.arrival_time, 预计到货时间
     */
    public void setArrivalTime(Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * 获取 物资状态1为可用，0不可用 字段:pur_purchase_order_goods.status
     *
     * @return pur_purchase_order_goods.status, 物资状态1为可用，0不可用
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 物资状态1为可用，0不可用 字段:pur_purchase_order_goods.status
     *
     * @param status the value for pur_purchase_order_goods.status, 物资状态1为可用，0不可用
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * ,pur_purchase_order_goods
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", purchaseInquiryId=").append(purchaseInquiryId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", type=").append(type);
        sb.append(", brand=").append(brand);
        sb.append(", colour=").append(colour);
        sb.append(", unit=").append(unit);
        sb.append(", norm=").append(norm);
        sb.append(", remark=").append(remark);
        sb.append(", unitPrice=").append(unitPrice);
        sb.append(", price=").append(price);
        sb.append(", quantity=").append(quantity);
        sb.append(", instoreNum=").append(instoreNum);
        sb.append(", supplier=").append(supplier);
        sb.append(", arrivalTime=").append(arrivalTime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}