package com.ddsh.util.service.api.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PurPurchaseOrderCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_order
     *
     * @mbg.generated
     */
    protected Integer pageNo = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_order
     *
     * @mbg.generated
     */
    protected Integer startRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_order
     *
     * @mbg.generated
     */
    protected Integer pageSize = 10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_order
     *
     * @mbg.generated
     */
    protected String fields;

    /**
     *  构造查询条件,pur_purchase_order
     */
    public PurPurchaseOrderCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,pur_purchase_order
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,pur_purchase_order
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,pur_purchase_order
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,pur_purchase_order
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,pur_purchase_order
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,pur_purchase_order
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,pur_purchase_order
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,pur_purchase_order
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,pur_purchase_order
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,pur_purchase_order
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,pur_purchase_order
     *
     * @param pageNo
     */
    public void setPageNo(Integer pageNo) {
        this.pageNo=pageNo;
        this.startRow = (pageNo-1)*this.pageSize;
    }

    /**
     * ,pur_purchase_order
     */
    public Integer getPageNo() {
        return pageNo;
    }

    /**
     * ,pur_purchase_order
     *
     * @param startRow
     */
    public void setStartRow(Integer startRow) {
        this.startRow=startRow;
    }

    /**
     * ,pur_purchase_order
     */
    public Integer getStartRow() {
        return startRow;
    }

    /**
     * ,pur_purchase_order
     *
     * @param pageSize
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize=pageSize;
        this.startRow = (pageNo-1)*this.pageSize;
    }

    /**
     * ,pur_purchase_order
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * ,pur_purchase_order
     *
     * @param fields
     */
    public void setFields(String fields) {
        this.fields=fields;
    }

    /**
     * ,pur_purchase_order
     */
    public String getFields() {
        return fields;
    }

    /**
     * 询价申请单
     * GeneratedCriteria
     * 数据库表：pur_purchase_order
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdIsNull() {
            addCriterion("initiateuser_id is null");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdIsNotNull() {
            addCriterion("initiateuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdEqualTo(String value) {
            addCriterion("initiateuser_id =", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdNotEqualTo(String value) {
            addCriterion("initiateuser_id <>", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdGreaterThan(String value) {
            addCriterion("initiateuser_id >", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdGreaterThanOrEqualTo(String value) {
            addCriterion("initiateuser_id >=", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdLessThan(String value) {
            addCriterion("initiateuser_id <", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdLessThanOrEqualTo(String value) {
            addCriterion("initiateuser_id <=", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdLike(String value) {
            addCriterion("initiateuser_id like", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdNotLike(String value) {
            addCriterion("initiateuser_id not like", value, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdIn(List<String> values) {
            addCriterion("initiateuser_id in", values, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdNotIn(List<String> values) {
            addCriterion("initiateuser_id not in", values, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdBetween(String value1, String value2) {
            addCriterion("initiateuser_id between", value1, value2, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserIdNotBetween(String value1, String value2) {
            addCriterion("initiateuser_id not between", value1, value2, "initiateuserId");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameIsNull() {
            addCriterion("initiateuser_name is null");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameIsNotNull() {
            addCriterion("initiateuser_name is not null");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameEqualTo(String value) {
            addCriterion("initiateuser_name =", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameNotEqualTo(String value) {
            addCriterion("initiateuser_name <>", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameGreaterThan(String value) {
            addCriterion("initiateuser_name >", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameGreaterThanOrEqualTo(String value) {
            addCriterion("initiateuser_name >=", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameLessThan(String value) {
            addCriterion("initiateuser_name <", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameLessThanOrEqualTo(String value) {
            addCriterion("initiateuser_name <=", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameLike(String value) {
            addCriterion("initiateuser_name like", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameNotLike(String value) {
            addCriterion("initiateuser_name not like", value, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameIn(List<String> values) {
            addCriterion("initiateuser_name in", values, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameNotIn(List<String> values) {
            addCriterion("initiateuser_name not in", values, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameBetween(String value1, String value2) {
            addCriterion("initiateuser_name between", value1, value2, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateuserNameNotBetween(String value1, String value2) {
            addCriterion("initiateuser_name not between", value1, value2, "initiateuserName");
            return (Criteria) this;
        }

        public Criteria andAudituserIdIsNull() {
            addCriterion("audituser_id is null");
            return (Criteria) this;
        }

        public Criteria andAudituserIdIsNotNull() {
            addCriterion("audituser_id is not null");
            return (Criteria) this;
        }

        public Criteria andAudituserIdEqualTo(String value) {
            addCriterion("audituser_id =", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdNotEqualTo(String value) {
            addCriterion("audituser_id <>", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdGreaterThan(String value) {
            addCriterion("audituser_id >", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdGreaterThanOrEqualTo(String value) {
            addCriterion("audituser_id >=", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdLessThan(String value) {
            addCriterion("audituser_id <", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdLessThanOrEqualTo(String value) {
            addCriterion("audituser_id <=", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdLike(String value) {
            addCriterion("audituser_id like", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdNotLike(String value) {
            addCriterion("audituser_id not like", value, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdIn(List<String> values) {
            addCriterion("audituser_id in", values, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdNotIn(List<String> values) {
            addCriterion("audituser_id not in", values, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdBetween(String value1, String value2) {
            addCriterion("audituser_id between", value1, value2, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserIdNotBetween(String value1, String value2) {
            addCriterion("audituser_id not between", value1, value2, "audituserId");
            return (Criteria) this;
        }

        public Criteria andAudituserNameIsNull() {
            addCriterion("audituser_name is null");
            return (Criteria) this;
        }

        public Criteria andAudituserNameIsNotNull() {
            addCriterion("audituser_name is not null");
            return (Criteria) this;
        }

        public Criteria andAudituserNameEqualTo(String value) {
            addCriterion("audituser_name =", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameNotEqualTo(String value) {
            addCriterion("audituser_name <>", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameGreaterThan(String value) {
            addCriterion("audituser_name >", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameGreaterThanOrEqualTo(String value) {
            addCriterion("audituser_name >=", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameLessThan(String value) {
            addCriterion("audituser_name <", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameLessThanOrEqualTo(String value) {
            addCriterion("audituser_name <=", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameLike(String value) {
            addCriterion("audituser_name like", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameNotLike(String value) {
            addCriterion("audituser_name not like", value, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameIn(List<String> values) {
            addCriterion("audituser_name in", values, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameNotIn(List<String> values) {
            addCriterion("audituser_name not in", values, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameBetween(String value1, String value2) {
            addCriterion("audituser_name between", value1, value2, "audituserName");
            return (Criteria) this;
        }

        public Criteria andAudituserNameNotBetween(String value1, String value2) {
            addCriterion("audituser_name not between", value1, value2, "audituserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdIsNull() {
            addCriterion("decisionuser_id is null");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdIsNotNull() {
            addCriterion("decisionuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdEqualTo(String value) {
            addCriterion("decisionuser_id =", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdNotEqualTo(String value) {
            addCriterion("decisionuser_id <>", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdGreaterThan(String value) {
            addCriterion("decisionuser_id >", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdGreaterThanOrEqualTo(String value) {
            addCriterion("decisionuser_id >=", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdLessThan(String value) {
            addCriterion("decisionuser_id <", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdLessThanOrEqualTo(String value) {
            addCriterion("decisionuser_id <=", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdLike(String value) {
            addCriterion("decisionuser_id like", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdNotLike(String value) {
            addCriterion("decisionuser_id not like", value, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdIn(List<String> values) {
            addCriterion("decisionuser_id in", values, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdNotIn(List<String> values) {
            addCriterion("decisionuser_id not in", values, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdBetween(String value1, String value2) {
            addCriterion("decisionuser_id between", value1, value2, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserIdNotBetween(String value1, String value2) {
            addCriterion("decisionuser_id not between", value1, value2, "decisionuserId");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameIsNull() {
            addCriterion("decisionuser_name is null");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameIsNotNull() {
            addCriterion("decisionuser_name is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameEqualTo(String value) {
            addCriterion("decisionuser_name =", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameNotEqualTo(String value) {
            addCriterion("decisionuser_name <>", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameGreaterThan(String value) {
            addCriterion("decisionuser_name >", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameGreaterThanOrEqualTo(String value) {
            addCriterion("decisionuser_name >=", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameLessThan(String value) {
            addCriterion("decisionuser_name <", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameLessThanOrEqualTo(String value) {
            addCriterion("decisionuser_name <=", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameLike(String value) {
            addCriterion("decisionuser_name like", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameNotLike(String value) {
            addCriterion("decisionuser_name not like", value, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameIn(List<String> values) {
            addCriterion("decisionuser_name in", values, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameNotIn(List<String> values) {
            addCriterion("decisionuser_name not in", values, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameBetween(String value1, String value2) {
            addCriterion("decisionuser_name between", value1, value2, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andDecisionuserNameNotBetween(String value1, String value2) {
            addCriterion("decisionuser_name not between", value1, value2, "decisionuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdIsNull() {
            addCriterion("purchaseuser_id is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdIsNotNull() {
            addCriterion("purchaseuser_id is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdEqualTo(String value) {
            addCriterion("purchaseuser_id =", value, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdNotEqualTo(String value) {
            addCriterion("purchaseuser_id <>", value, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdGreaterThan(String value) {
            addCriterion("purchaseuser_id >", value, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdGreaterThanOrEqualTo(String value) {
            addCriterion("purchaseuser_id >=", value, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdLessThan(String value) {
            addCriterion("purchaseuser_id <", value, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdLessThanOrEqualTo(String value) {
            addCriterion("purchaseuser_id <=", value, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdLike(String value) {
            addCriterion("purchaseuser_id like", value, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdNotLike(String value) {
            addCriterion("purchaseuser_id not like", value, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdIn(List<String> values) {
            addCriterion("purchaseuser_id in", values, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdNotIn(List<String> values) {
            addCriterion("purchaseuser_id not in", values, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdBetween(String value1, String value2) {
            addCriterion("purchaseuser_id between", value1, value2, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserIdNotBetween(String value1, String value2) {
            addCriterion("purchaseuser_id not between", value1, value2, "purchaseuserId");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameIsNull() {
            addCriterion("purchaseuser_name is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameIsNotNull() {
            addCriterion("purchaseuser_name is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameEqualTo(String value) {
            addCriterion("purchaseuser_name =", value, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameNotEqualTo(String value) {
            addCriterion("purchaseuser_name <>", value, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameGreaterThan(String value) {
            addCriterion("purchaseuser_name >", value, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameGreaterThanOrEqualTo(String value) {
            addCriterion("purchaseuser_name >=", value, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameLessThan(String value) {
            addCriterion("purchaseuser_name <", value, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameLessThanOrEqualTo(String value) {
            addCriterion("purchaseuser_name <=", value, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameLike(String value) {
            addCriterion("purchaseuser_name like", value, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameNotLike(String value) {
            addCriterion("purchaseuser_name not like", value, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameIn(List<String> values) {
            addCriterion("purchaseuser_name in", values, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameNotIn(List<String> values) {
            addCriterion("purchaseuser_name not in", values, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameBetween(String value1, String value2) {
            addCriterion("purchaseuser_name between", value1, value2, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andPurchaseuserNameNotBetween(String value1, String value2) {
            addCriterion("purchaseuser_name not between", value1, value2, "purchaseuserName");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeIsNull() {
            addCriterion("initiate_time is null");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeIsNotNull() {
            addCriterion("initiate_time is not null");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeEqualTo(Date value) {
            addCriterion("initiate_time =", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeNotEqualTo(Date value) {
            addCriterion("initiate_time <>", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeGreaterThan(Date value) {
            addCriterion("initiate_time >", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("initiate_time >=", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeLessThan(Date value) {
            addCriterion("initiate_time <", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeLessThanOrEqualTo(Date value) {
            addCriterion("initiate_time <=", value, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeIn(List<Date> values) {
            addCriterion("initiate_time in", values, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeNotIn(List<Date> values) {
            addCriterion("initiate_time not in", values, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeBetween(Date value1, Date value2) {
            addCriterion("initiate_time between", value1, value2, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andInitiateTimeNotBetween(Date value1, Date value2) {
            addCriterion("initiate_time not between", value1, value2, "initiateTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeIsNull() {
            addCriterion("decision_time is null");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeIsNotNull() {
            addCriterion("decision_time is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeEqualTo(Date value) {
            addCriterion("decision_time =", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeNotEqualTo(Date value) {
            addCriterion("decision_time <>", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeGreaterThan(Date value) {
            addCriterion("decision_time >", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("decision_time >=", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeLessThan(Date value) {
            addCriterion("decision_time <", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeLessThanOrEqualTo(Date value) {
            addCriterion("decision_time <=", value, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeIn(List<Date> values) {
            addCriterion("decision_time in", values, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeNotIn(List<Date> values) {
            addCriterion("decision_time not in", values, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeBetween(Date value1, Date value2) {
            addCriterion("decision_time between", value1, value2, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andDecisionTimeNotBetween(Date value1, Date value2) {
            addCriterion("decision_time not between", value1, value2, "decisionTime");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionIsNull() {
            addCriterion("leader_decision is null");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionIsNotNull() {
            addCriterion("leader_decision is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionEqualTo(BigDecimal value) {
            addCriterion("leader_decision =", value, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionNotEqualTo(BigDecimal value) {
            addCriterion("leader_decision <>", value, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionGreaterThan(BigDecimal value) {
            addCriterion("leader_decision >", value, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("leader_decision >=", value, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionLessThan(BigDecimal value) {
            addCriterion("leader_decision <", value, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("leader_decision <=", value, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionIn(List<BigDecimal> values) {
            addCriterion("leader_decision in", values, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionNotIn(List<BigDecimal> values) {
            addCriterion("leader_decision not in", values, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leader_decision between", value1, value2, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andLeaderDecisionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leader_decision not between", value1, value2, "leaderDecision");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeIsNull() {
            addCriterion("purchase_time is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeIsNotNull() {
            addCriterion("purchase_time is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeEqualTo(Date value) {
            addCriterion("purchase_time =", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeNotEqualTo(Date value) {
            addCriterion("purchase_time <>", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeGreaterThan(Date value) {
            addCriterion("purchase_time >", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("purchase_time >=", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeLessThan(Date value) {
            addCriterion("purchase_time <", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeLessThanOrEqualTo(Date value) {
            addCriterion("purchase_time <=", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeIn(List<Date> values) {
            addCriterion("purchase_time in", values, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeNotIn(List<Date> values) {
            addCriterion("purchase_time not in", values, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeBetween(Date value1, Date value2) {
            addCriterion("purchase_time between", value1, value2, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeNotBetween(Date value1, Date value2) {
            addCriterion("purchase_time not between", value1, value2, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceIsNull() {
            addCriterion("inquiry_price is null");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceIsNotNull() {
            addCriterion("inquiry_price is not null");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceEqualTo(BigDecimal value) {
            addCriterion("inquiry_price =", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceNotEqualTo(BigDecimal value) {
            addCriterion("inquiry_price <>", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceGreaterThan(BigDecimal value) {
            addCriterion("inquiry_price >", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("inquiry_price >=", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceLessThan(BigDecimal value) {
            addCriterion("inquiry_price <", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("inquiry_price <=", value, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceIn(List<BigDecimal> values) {
            addCriterion("inquiry_price in", values, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceNotIn(List<BigDecimal> values) {
            addCriterion("inquiry_price not in", values, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inquiry_price between", value1, value2, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andInquiryPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inquiry_price not between", value1, value2, "inquiryPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceIsNull() {
            addCriterion("purchase_price is null");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceIsNotNull() {
            addCriterion("purchase_price is not null");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceEqualTo(BigDecimal value) {
            addCriterion("purchase_price =", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceNotEqualTo(BigDecimal value) {
            addCriterion("purchase_price <>", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceGreaterThan(BigDecimal value) {
            addCriterion("purchase_price >", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("purchase_price >=", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceLessThan(BigDecimal value) {
            addCriterion("purchase_price <", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("purchase_price <=", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceIn(List<BigDecimal> values) {
            addCriterion("purchase_price in", values, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceNotIn(List<BigDecimal> values) {
            addCriterion("purchase_price not in", values, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("purchase_price between", value1, value2, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("purchase_price not between", value1, value2, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkIsNull() {
            addCriterion("initiate_remark is null");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkIsNotNull() {
            addCriterion("initiate_remark is not null");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkEqualTo(String value) {
            addCriterion("initiate_remark =", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkNotEqualTo(String value) {
            addCriterion("initiate_remark <>", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkGreaterThan(String value) {
            addCriterion("initiate_remark >", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("initiate_remark >=", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkLessThan(String value) {
            addCriterion("initiate_remark <", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkLessThanOrEqualTo(String value) {
            addCriterion("initiate_remark <=", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkLike(String value) {
            addCriterion("initiate_remark like", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkNotLike(String value) {
            addCriterion("initiate_remark not like", value, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkIn(List<String> values) {
            addCriterion("initiate_remark in", values, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkNotIn(List<String> values) {
            addCriterion("initiate_remark not in", values, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkBetween(String value1, String value2) {
            addCriterion("initiate_remark between", value1, value2, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andInitiateRemarkNotBetween(String value1, String value2) {
            addCriterion("initiate_remark not between", value1, value2, "initiateRemark");
            return (Criteria) this;
        }

        public Criteria andStepIsNull() {
            addCriterion("step is null");
            return (Criteria) this;
        }

        public Criteria andStepIsNotNull() {
            addCriterion("step is not null");
            return (Criteria) this;
        }

        public Criteria andStepEqualTo(Integer value) {
            addCriterion("step =", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotEqualTo(Integer value) {
            addCriterion("step <>", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThan(Integer value) {
            addCriterion("step >", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThanOrEqualTo(Integer value) {
            addCriterion("step >=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThan(Integer value) {
            addCriterion("step <", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThanOrEqualTo(Integer value) {
            addCriterion("step <=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepIn(List<Integer> values) {
            addCriterion("step in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotIn(List<Integer> values) {
            addCriterion("step not in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepBetween(Integer value1, Integer value2) {
            addCriterion("step between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotBetween(Integer value1, Integer value2) {
            addCriterion("step not between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andAuditResultIsNull() {
            addCriterion("audit_result is null");
            return (Criteria) this;
        }

        public Criteria andAuditResultIsNotNull() {
            addCriterion("audit_result is not null");
            return (Criteria) this;
        }

        public Criteria andAuditResultEqualTo(Integer value) {
            addCriterion("audit_result =", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotEqualTo(Integer value) {
            addCriterion("audit_result <>", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultGreaterThan(Integer value) {
            addCriterion("audit_result >", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_result >=", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultLessThan(Integer value) {
            addCriterion("audit_result <", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultLessThanOrEqualTo(Integer value) {
            addCriterion("audit_result <=", value, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultIn(List<Integer> values) {
            addCriterion("audit_result in", values, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotIn(List<Integer> values) {
            addCriterion("audit_result not in", values, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultBetween(Integer value1, Integer value2) {
            addCriterion("audit_result between", value1, value2, "auditResult");
            return (Criteria) this;
        }

        public Criteria andAuditResultNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_result not between", value1, value2, "auditResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultIsNull() {
            addCriterion("decision_result is null");
            return (Criteria) this;
        }

        public Criteria andDecisionResultIsNotNull() {
            addCriterion("decision_result is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionResultEqualTo(Integer value) {
            addCriterion("decision_result =", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultNotEqualTo(Integer value) {
            addCriterion("decision_result <>", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultGreaterThan(Integer value) {
            addCriterion("decision_result >", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("decision_result >=", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultLessThan(Integer value) {
            addCriterion("decision_result <", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultLessThanOrEqualTo(Integer value) {
            addCriterion("decision_result <=", value, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultIn(List<Integer> values) {
            addCriterion("decision_result in", values, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultNotIn(List<Integer> values) {
            addCriterion("decision_result not in", values, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultBetween(Integer value1, Integer value2) {
            addCriterion("decision_result between", value1, value2, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionResultNotBetween(Integer value1, Integer value2) {
            addCriterion("decision_result not between", value1, value2, "decisionResult");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkIsNull() {
            addCriterion("decision_remark is null");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkIsNotNull() {
            addCriterion("decision_remark is not null");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkEqualTo(String value) {
            addCriterion("decision_remark =", value, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkNotEqualTo(String value) {
            addCriterion("decision_remark <>", value, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkGreaterThan(String value) {
            addCriterion("decision_remark >", value, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("decision_remark >=", value, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkLessThan(String value) {
            addCriterion("decision_remark <", value, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkLessThanOrEqualTo(String value) {
            addCriterion("decision_remark <=", value, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkLike(String value) {
            addCriterion("decision_remark like", value, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkNotLike(String value) {
            addCriterion("decision_remark not like", value, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkIn(List<String> values) {
            addCriterion("decision_remark in", values, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkNotIn(List<String> values) {
            addCriterion("decision_remark not in", values, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkBetween(String value1, String value2) {
            addCriterion("decision_remark between", value1, value2, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andDecisionRemarkNotBetween(String value1, String value2) {
            addCriterion("decision_remark not between", value1, value2, "decisionRemark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkIsNull() {
            addCriterion("purchase_remark is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkIsNotNull() {
            addCriterion("purchase_remark is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkEqualTo(String value) {
            addCriterion("purchase_remark =", value, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkNotEqualTo(String value) {
            addCriterion("purchase_remark <>", value, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkGreaterThan(String value) {
            addCriterion("purchase_remark >", value, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("purchase_remark >=", value, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkLessThan(String value) {
            addCriterion("purchase_remark <", value, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkLessThanOrEqualTo(String value) {
            addCriterion("purchase_remark <=", value, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkLike(String value) {
            addCriterion("purchase_remark like", value, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkNotLike(String value) {
            addCriterion("purchase_remark not like", value, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkIn(List<String> values) {
            addCriterion("purchase_remark in", values, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkNotIn(List<String> values) {
            addCriterion("purchase_remark not in", values, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkBetween(String value1, String value2) {
            addCriterion("purchase_remark between", value1, value2, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andPurchaseRemarkNotBetween(String value1, String value2) {
            addCriterion("purchase_remark not between", value1, value2, "purchaseRemark");
            return (Criteria) this;
        }

        public Criteria andOtherPriceIsNull() {
            addCriterion("other_price is null");
            return (Criteria) this;
        }

        public Criteria andOtherPriceIsNotNull() {
            addCriterion("other_price is not null");
            return (Criteria) this;
        }

        public Criteria andOtherPriceEqualTo(BigDecimal value) {
            addCriterion("other_price =", value, "otherPrice");
            return (Criteria) this;
        }

        public Criteria andOtherPriceNotEqualTo(BigDecimal value) {
            addCriterion("other_price <>", value, "otherPrice");
            return (Criteria) this;
        }

        public Criteria andOtherPriceGreaterThan(BigDecimal value) {
            addCriterion("other_price >", value, "otherPrice");
            return (Criteria) this;
        }

        public Criteria andOtherPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("other_price >=", value, "otherPrice");
            return (Criteria) this;
        }

        public Criteria andOtherPriceLessThan(BigDecimal value) {
            addCriterion("other_price <", value, "otherPrice");
            return (Criteria) this;
        }

        public Criteria andOtherPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("other_price <=", value, "otherPrice");
            return (Criteria) this;
        }

        public Criteria andOtherPriceIn(List<BigDecimal> values) {
            addCriterion("other_price in", values, "otherPrice");
            return (Criteria) this;
        }

        public Criteria andOtherPriceNotIn(List<BigDecimal> values) {
            addCriterion("other_price not in", values, "otherPrice");
            return (Criteria) this;
        }

        public Criteria andOtherPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("other_price between", value1, value2, "otherPrice");
            return (Criteria) this;
        }

        public Criteria andOtherPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("other_price not between", value1, value2, "otherPrice");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：pur_purchase_order
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 询价申请单
     * Criterion
     * 数据库表：pur_purchase_order
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}