package com.ddsh.util.service.api.model;

import java.io.Serializable;

public class PurPurchaseToStore implements Serializable {
    /**
     * 主键ID
     * 表字段 : pur_purchase_to_store.id
     */
    private String id;

    /**
     * 采购单ID
     * 表字段 : pur_purchase_to_store.purchase_id
     */
    private String purchaseId;

    /**
     * 仓库ID
     * 表字段 : pur_purchase_to_store.store_id
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pur_purchase_to_store
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键ID 字段:pur_purchase_to_store.id
     *
     * @return pur_purchase_to_store.id, 主键ID
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 主键ID 字段:pur_purchase_to_store.id
     *
     * @param id the value for pur_purchase_to_store.id, 主键ID
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 采购单ID 字段:pur_purchase_to_store.purchase_id
     *
     * @return pur_purchase_to_store.purchase_id, 采购单ID
     */
    public String getPurchaseId() {
        return purchaseId;
    }

    /**
     * 设置 采购单ID 字段:pur_purchase_to_store.purchase_id
     *
     * @param purchaseId the value for pur_purchase_to_store.purchase_id, 采购单ID
     */
    public void setPurchaseId(String purchaseId) {
        this.purchaseId = purchaseId == null ? null : purchaseId.trim();
    }

    /**
     * 获取 仓库ID 字段:pur_purchase_to_store.store_id
     *
     * @return pur_purchase_to_store.store_id, 仓库ID
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 设置 仓库ID 字段:pur_purchase_to_store.store_id
     *
     * @param storeId the value for pur_purchase_to_store.store_id, 仓库ID
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * ,pur_purchase_to_store
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", purchaseId=").append(purchaseId);
        sb.append(", storeId=").append(storeId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}